// ==========================================
// 🧠 BÓVEDA DE PROMPTS AGIA 2.0 - SECURE DB
// Encrypted Content. Key required to decrypt.
// ==========================================

const allCases = [
    {
        "id": 101,
        "category": "productivity",
        "title": "El Filtra-Correos: De Caos a Inbox Zero",
        "icon": "inbox_customize",
        "problem": "Email: Gestión ineficiente de bandeja de entrada saturada.",
        "badPrompt": "Resume mis correos pendientes y dime qué es importante.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Tienes 10 correos. 3 son de clientes, 2 de facturas y el resto es publicidad. Debes responder a los clientes pronto.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/bl+uiFu6PYVjykxXpdDdzkAtMf6Z/QgMyMg2cEsS2bfA3lFr6OL5MisXjGKBerCqq0PU8lyOd3Uo+u6XV/FcfLdcpIHJBnIrBOzHTHb2y6ubW2TNM/6YFdcky3YkQTq2dwM9eAnZTjo/GN/L9iBk5Q1esKYODY/HaRMuG9wn/xYDhBV69e6o4R9dhRtWxgC4dX3kEXmVW0+d62RsPSbK5egAyto3XM6vFVxu2Qg8RkvHN6xmnXT/6H9Zsi5nBGmOilxRFSHJrrHlNX8KhBZl94OI1PedX7/150Q7gGzjlkcdF/kFzTI22L/YolrGC7AaLd5FNQxKjLmWcuhxT89J01/Gvc49hPIV3srHc1S7PIj7LfwHk+KhFA9B3a/1N9sSBrltU2FcXY3wDayINPzYPxQbt3kthexgdsYuZDnXpibrYn/ADYejMHJPiczcvyLLRB3lytIYaeHRHjacQnZa8cynw9WhdJLyGnJ65+lRDNllsMIdBA8KuyvNIVlfFV+/xruGVbb3Epxz+EiFt/BREYKZzoiMld/mr7gXzLdEKkyuHvlJEVMoCRVP/0SAppSnZ5uHw9oJzilp4St3imZIw5CgYb4GBE7DtOJzMHjlQgT2bAGLYcgBIzD5R5gUx0ClcEMYfdklfXsJmh89yJHHS8MZFwCT8uWkAaQW2SvJxVyGRPC0MKc2OO7ctO5JvxLD1WMetXNj4rltg/aCA95tpMb/uaJ9OXB1+aDeZ8Jv/Yyv/0zBGGIjIfCf7M/SFwk4JRAJhUaPNUw==",
        "exampleTip": "Classification & Zero-Shot Prompting (Clasifica datos sin ejemplos previos basados en reglas estrictas).",
        "validationTip": "¿Puedes identificar qué hacer en menos de 10 segundos mirando la tabla?",
        "previewResponse": "<div class=\"overflow-x-auto text-[10px]\"><table class=\"w-full border-collapse\"><thead><tr class=\"bg-slate-100\"><th>Remitente</th><th>Resumen Crítico</th><th>Acción Sugerida</th></tr></thead><tbody><tr><td>Juan Pérez</td><td>Consulta por retraso en envío Starken.</td><td class=\"text-red-600 font-bold\">Responder hoy: Pedir disculpas y adjuntar número de seguimiento.</td></tr><tr><td>Tesorería</td><td>Aviso de factura vencida (Internet).</td><td>Informativo: Programar pago para el viernes.</td></tr><tr><td>María Paz</td><td>Pide reunión para ver presupuesto Aula GenIA.</td><td class=\"text-red-600 font-bold\">Responder hoy: Enviar link de Calendly para el martes.</td></tr></tbody></table><div class=\"mt-2 p-1 bg-blue-50 border-l-2 border-blue-400 font-mono italic\"><strong>Borrador Sugerido (Juan):</strong> \"Hola Juan, te pido mil disculpas por la demora. Aquí tienes el número de seguimiento de Starken: [Número]. Mañana debería estar en tu oficina. Saludos!\"</div></div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 102,
        "category": "productivity",
        "title": "Ninja de Actas: De Reunión Eterna a Tareas Claras",
        "icon": "groups",
        "problem": "Gestión: Pérdida de tiempo en reuniones sin acuerdos claros.",
        "badPrompt": "Haz un resumen de esta transcripción de reunión.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"En la reunión hablaron sobre el nuevo logo, el presupuesto de marketing y que se van a juntar el próximo jueves.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1+0GVtSiDMfS52RHju5SAoPHhSd8MMibAUII3HAbDoAd7FNjMnhyA2GNpCYLHRrBPRd19Ea2Vz15wthLnmynESPaE/6QuWmZZA3hq5O7VGAjQ/Ng98eCclI1fIZttGhlU7aVXdPE3iuQ9aBiGKux4q9PYhs/MRfqPSTf550yUA9Q0BbxkajgSH91TIIMx8N7th/jJGuL7xW//W3cIr7S8Fv4Pib8QalqR0BlrP8SeFNRAkqmdpfSs4CQHgpBzy1SSodzLJl2hl09j/yTPWMfImkuLCXvkJBB9j++YNJHqr+PqgjmsgkrL/iLtigrE4D5jhWqdMgTK5eVBYAN4kvjiBqKJ1FBNBT6IDZPiwStmWrWwWxM4nn1fh2rqGi3OLSKSPer9OZfY9AIE1P1EWOA7ALF+v4zmhThUCXW0i1w6ePJSUFR29y3JydwIXD5IxsureefJu0IRL0MjAm7leqHPl2MaCbTCeTrtIkGfJgGbOFlP9GR+fZPByBKGfmgX5NFrbPzAa7if2LBUMEMZJ8aUPbMEMzyd149RkwcA/0HXlSOAybqVlbWOYIpwV1u73aUeDRVkoyOaek+H3EvM58LbmsNgrlrCJCl8SgVlpSNG+9yDJ26yrJgzWUQdNSAVQ7Aypk+pox1bIrWw==",
        "exampleTip": "Information Extraction & Structured Output (Fuerza a la IA a ignorar el 'ruido' y enfocarse en datos accionables).",
        "validationTip": "¿Si alguien no fue a la reunión, entiende perfectamente qué debe hacer?",
        "previewResponse": "<div class=\"text-[10px]\"><p><strong>Resumen:</strong> Se aprueba el aumento de presupuesto para Ads pero se pausa el diseño de la web.</p><p class=\"mt-1 font-bold\">Decisiones Clave:</p><ul class=\"list-disc ml-3\"><li>No se contratará agencia externa este mes.</li><li>El lanzamiento se mueve al 15 de enero.</li></ul><table class=\"w-full mt-1 border border-slate-200 border-collapse\"><thead class=\"bg-slate-50\"><tr><th class=\"border p-1\">Tarea</th><th class=\"border p-1\">Responsable</th><th class=\"border p-1\">Plazo</th></tr></thead><tbody><tr><td class=\"border p-1\">Ajustar presupuesto en Excel</td><td class=\"border p-1\">Pedro</td><td class=\"border p-1\">Lunes</td></tr><tr><td class=\"border p-1\">Enviar diseño final a imprenta</td><td class=\"border p-1\">Carola</td><td class=\"border p-1\">Miércoles</td></tr><tr><td class=\"border p-1\">Dejar constancia en Carabineros por pérdida de equipo</td><td class=\"border p-1\">Don Lucho</td><td class=\"border p-1\">Mañana</td></tr></tbody></table></div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 103,
        "category": "productivity",
        "title": "El Explicador \"Feynman\": Aprende lo que sea en minutos",
        "icon": "psychology",
        "problem": "Aprendizaje: Conceptos complejos difíciles de asimilar o explicar.",
        "badPrompt": "Explícame qué es el Blockchain.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"El blockchain es un libro de contabilidad digital descentralizado que registra transacciones en muchas computadoras para que el registro no se pueda alterar retroactivamente.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1+cDrpv/xL+lzy2Y4Rhfx1B0eZQgZiI8GEwED55uC6vLJMn52JfWkVTP41PoBfbGnRs9Qx/fMCBxaYrEDeL6tqfod4bAicOhzR0kFStG4Vo4tYiKPxx8d2NWzr22jnPXPPi08nBuVYtmk56RyBWFRi8GFrsk7HUQkAXStRNnx6rbhPFCrH/d4t95C8lWn6HlBhI/y2FIoFliSqTogjvpv0STGrWD/VpD1Mx5wmmtsqKcoOZD4tppkd0fesfUzgFY1mWwagZ+Gqe8yjBlh3QLEwYhSxXqmLeRsSgaUoBfc1+TLQ5fZtyiVe2oASucIYYzPF1S8/lzWvz+az5aerT9Kl++bOgIv9LDUgw3iyJGTlOq2v+lNt0B9dAs7Vr3+a/CPE3Jr6kx68KyXTCOG+OxM5Xech5Iz+Hy7nmm93VIxoqN/sWvfZT4iIRSTyzNmqiR+ZAQAhufX1hNlRR7q2a0Bs+ocqsTe5oGtT38DM98P3FohU2TAHzpPIuTe2rbQD5E4juwoRELIxASPINepdzev+vy6ypczjzNu0t8unzMKwXz3I7ageH0qTI2lLmIbL1qWexYxqtUWVarVo7npUdWillghZwWXaZXTQOCc7j1Zx/g8AiqWuC0DU6egUrJWXrsElYr0I0UJVy7iOXtm5Bn65/9qsUsdUd/fkmOC13ggydiPt7v3WOXNHqWJ+XOr3vuzsgOK3vaVKrk4BDJE1eb6LSJJdF338kSAU=",
        "exampleTip": "Analogical Reasoning (Mejora la retención de información vinculando datos nuevos a conceptos conocidos).",
        "validationTip": "¿Podrías explicarle esto a tu abuela o a tu hija de 4 años y que lo entiendan?",
        "previewResponse": "<div class=\"p-2 bg-yellow-50 border border-yellow-200 text-[10px] rounded\"><p><strong>El SII explicado como una Junta de Vecinos:</strong></p><p>Imagínate que vives en una comunidad. Para que las luces de la calle funcionen y la plaza esté bonita, todos deben poner una cuota mensual. El SII es como el \"Tesorero\" de la junta de vecinos.</p><p class=\"mt-1\"><strong>Concepto Clave:</strong> Él revisa cuánto dinero ganaste (tus boletas) para decirte cuánto toca poner para la plaza (los impuestos).</p><p class=\"mt-1\"><strong>Ejemplo Práctico:</strong> Si vendiste 10 tortas, el SII sabe que ganaste $100.000. Te dice: \"De esos $100.000, $19.000 son el IVA (la cuota de la plaza)\". No es dinero tuyo, solo lo estás guardando para entregárselo a él.</p></div>",
        "suggestedAI": "gemini",
        "locked": false,
        "isTool": false,
        "difficulty": "beginner"
    },
    {
        "id": 104,
        "category": "productivity",
        "title": "Estructurador de Cursos Relámpago",
        "icon": "school",
        "problem": "Educación: Planificación lenta de currículos educativos.",
        "badPrompt": "Hazme un temario para un curso de Excel.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"1. Introducción. 2. Fórmulas básicas. 3. Gráficos. 4. Tablas dinámicas. 5. Conclusión.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1890OcgUPWn87qucXy5BS9rLAm66qfGcnv8di62xfBs7V8luR1y9r/mWqzj22sxlHntTp+iW5sfrfpYHdNp4yiupPpTbZAQAvYBshZ/40t/Te8gw+v10brTxgHsxOvZFtBCO5/Q+kDKFsHugnHiO/GYiwz9DJr0+wEHJW2/h7wLYkEb3xF86PvSSV0Z0m3hKhv8eUyCUwEC+fD6I3us1ybKqIzRygeFKHj4+eF2CD/qXZUdQpStczrLtPM3nbwZ/vAuR0InYHBf4L38dOiWWtlc8BsVTKCjWS8ICsKJV88gbFwzAUvTD6eg89ap2+y/TTOE+Oi/NC4rG86kBBZyapWixS+0LnFUqeg4H2TZV06qVzI8RrWx2fyYILUZ6ylmMIH7RVncfA3rCrr59LsiOVbFAJqEm3K6Yn4uLVDjUV/oLd793sBH0S3VErRQUNiKfnobGbVcYG6svGw9cK1L1UMDvttsoS29SFQdyrpPPPueInnwbVHEZNq84fK57LUkV3q3e8ZWsNEHqHCTFDuFRNVUw1Osa/Gfb5B1HDcpqWy45cr+pn3NrBec32/b3scu6GUHL+drdQVNXgTfpeVWZ6zzdzOGWKvDDf23GO6j/KQA4mH25SMdk9NbUZJZckBfwrW3Goi92hcsWQ==",
        "exampleTip": "Backward Design (Planifica desde el resultado deseado hacia atrás para asegurar utilidad).",
        "validationTip": "¿El alumno termina el curso con algo real construido?",
        "previewResponse": "<div class=\"text-[10px]\"><p class=\"font-bold mb-1\">Estructura de \"Aula GenIA\" (4 Semanas):</p><table class=\"w-full border border-collapse text-left\"><thead><tr class=\"bg-indigo-50\"><th>Semana</th><th>Tema</th><th>Proyecto Práctico</th></tr></thead><tbody><tr><td>1</td><td>Domando a la IA: Prompts de Oro</td><td>Crear un asistente que redacte tus correos de venta.</td></tr><tr><td>2</td><td>Imágenes que Venden (Canva + AI)</td><td>Diseñar 3 posts de Instagram con modelos generados por IA.</td></tr><tr><td>3</td><td>Automatización con WhatsApp</td><td>Configurar respuestas automáticas para preguntas de precio.</td></tr><tr><td>4</td><td>Análisis de Negocio Express</td><td>Subir tu Excel de ventas y pedirle a la IA que encuentre tus fugas de plata.</td></tr></tbody></table></div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 105,
        "category": "productivity",
        "title": "Asistente de Informes \"Cero Paja\"",
        "icon": "description",
        "problem": "Reportabilidad: Informes largos, aburridos y poco accionables.",
        "badPrompt": "Escribe un informe sobre los resultados de ventas del mes.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Las ventas este mes fueron buenas. Subieron un 10% respecto al mes pasado. Estamos contentos y esperamos seguir así.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1+OXx9ZtSp1Jsm5ijhrcEFFueAyR9J1G8CCUDWGkS/Kbs/73mpTY2Am3YKkbBocZ3BHvPOUE2BujTHxvVv7U2BvbwYzIOuVfAltdeEezk+/ZkCe58/aprTx/kk5MuBF9SLsPRu0IaQTZeGLxmuYrZi2ubf1rni93TfQ394j9VmOHjuYbAwRe6CgMrcmFaMbtjHlfGZMNbU2Km6kPe6/FzDoMU7vw7LEsm585MtgipcvIc3sxfC4aThkwmODcgFIJL3qm4Esk1GU5NGAU+ms7+CLHjwAhUgU8Rf9mxPV9BStrFvIyWSBIUnT+XQVg8ukuGtLIgVJfA3P6Cv2pWaygLvK8haEHR8fL2MsLJkLdJwaVli1RSFdWDAcOTZzDafLGkacldzT4ESAs4wFe0FzihBYyRgAIcyYPxTit1W3YVzFoGGAtFwNK9b/bHer6Go7ss1Vw17FKH3LZ5++TrTLxc8xxXGO9kD+t0XoCWJXKVqoJb5Pvdha+B+NLOetewRNp1M6gG0nE+JX6sLuUgggsxArrX90j6Dnp2kfUJCSzpmH1W489lI9cYWC7uBj6BAYCgj021f/tTL7cm9zupVpO+xNuY1fhrQt38PLOBNDCQ/oJVGyvYVm4DlZ",
        "exampleTip": "BLUF Strategy (Prioriza la información crítica para ahorrar tiempo a los lectores).",
        "validationTip": "¿Si el jefe solo lee el primer párrafo, se entera de todo lo importante?",
        "previewResponse": "<div class=\"bg-white p-2 border shadow-sm text-[10px]\"><p><strong>RESUMEN EJECUTIVO (BLUF):</strong> Cerramos el mes con una utilidad neta de $3M (60% de margen), superando la meta en un 15%.</p><p class=\"mt-1 font-bold\">Insights Clave:</p><ul class=\"list-disc ml-3\"><li><strong>Eficiencia:</strong> Los gastos se mantuvieron estables.</li><li><strong>Concentración:</strong> El 40% de ingresos depende de \"Pyme X\"; riesgo alto.</li><li><strong>Canal:</strong> TikTok generó más leads que Instagram.</li></ul><p class=\"mt-1 font-bold\">Próximos Pasos:</p><ol class=\"list-decimal ml-3\"><li>Diversificar cartera: Captar 2 clientes nuevos.</li><li>Reasignar presupuesto de Ads a TikTok.</li></ol></div>",
        "suggestedAI": "gemini",
        "locked": false,
        "isTool": false,
        "difficulty": "advanced"
    },
    {
        "id": 106,
        "category": "productivity",
        "title": "Planificador de Jornada \"Anti-Procrastinación\"",
        "icon": "schedule",
        "problem": "Gestión: Listas de tareas infinitas que generan parálisis.",
        "badPrompt": "Organiza mi calendario de mañana, tengo mucho que hacer.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"9am: Correos. 10am: Reunión. 12pm: Almuerzo. 2pm: Trabajo. 5pm: Terminar.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX195y1/mIxtiydgT3Fq/Q33V07lP/58m4Zp/5/jT7B5j9A5jGuvt6FIfmX7aL1w0m4Q/U3P0/U2H4V8R9X0/O0/8r4f6V8s9T6x1c0v3k9d6p6l/i3m7a4d5e8o",
        "exampleTip": "Time Blocking & Energy Mapping (Optimiza no solo el tiempo, sino la capacidad mental disponible).",
        "validationTip": "¿Sientes que el horario es realista o te estresa solo verlo?",
        "previewResponse": "<div class=\"text-[10px] space-y-1\"><p class=\"font-bold\">Tu Plan Maestro de Mañana:</p><ul><li><strong>08:30 - 09:00:</strong> Logística familiar (Llevar hija al jardín). <em>Energía: Baja.</em></li><li><strong>09:15 - 11:15:</strong> 🧠 <strong>BLOQUE PROFUNDO:</strong> Grabar 5 videos de TikTok. <em>Energía: Máxima.</em></li><li><strong>11:15 - 11:45:</strong> Break & Buffer (Estirarse, café, imprevistos).</li><li><strong>11:45 - 13:00:</strong> Trabajo Administrativo (Pagar cuentas). <em>Energía: Media.</em></li><li><strong>13:00 - 14:00:</strong> Almuerzo (Lejos de la pantalla).</li><li><strong>14:00 - 15:30:</strong> Formación: Ver 2 módulos de Aula GenIA. <em>Energía: Media-Baja.</em></li></ul></div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "beginner"
    },
    {
        "id": 107,
        "category": "productivity",
        "title": "Traductor de Jerga Legal (Contratos)",
        "icon": "gavel",
        "problem": "Legal: Dificultad para entender contratos y riesgos legales.",
        "badPrompt": "Dime qué dice este contrato de arriendo.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Es un contrato de arriendo por 12 meses. Dice que tienes que pagar el 5 de cada mes y cuidar la propiedad.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX19q2t3h/t8p64n7o5/10m2/4p5/8q9/1r2s3t4u5v6w7x8y9z0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Risk Assessment Prompting (Enfoca la atención de la IA en anomalías y peligros potenciales).",
        "validationTip": "¿Sabes exactamente qué frase pedir que cambien en el contrato?",
        "previewResponse": "<div class=\"text-[10px] space-y-1\"><p class=\"font-bold\">Análisis de tu Contrato de Arriendo:</p><div>🟢 <strong>Verde:</strong> El reajuste por IPC es semestral, lo cual es estándar y justo.</div><div>🟡 <strong>Amarillo:</strong> Dice que debes avisar con 60 días si te vas. Lo normal son 30.</div><div>🔴 <strong>Rojo:</strong> Cláusula permite al dueño entrar \"cuando quiera\". <strong>Esto es ilegal.</strong></div><p class=\"mt-1 italic\"><strong>Fechas Críticas:</strong> Pago hasta el 5, al día 6 te cobran 1% diario de multa.</p></div>",
        "suggestedAI": "perplexity",
        "locked": false,
        "isTool": false,
        "difficulty": "advanced"
    },
    {
        "id": 108,
        "category": "productivity",
        "title": "Generador de Presentaciones Express",
        "icon": "slideshow",
        "problem": "Diseño: Diapositivas con mucho texto que nadie lee.",
        "badPrompt": "Hazme una presentación sobre marketing digital.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Diapositiva 1: Título. Diapositiva 2: Qué es marketing. Diapositiva 3: Redes sociales. Diapositiva 4: SEO. Diapositiva 5: Gracias.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX19w1x2y3z4a5b6c7d8e9f0g1h2i3j4k5l6m7n8o9p0q1r2s3t4u5v6w7x8y9z0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Visual Metaphor & Storylining (Crea una estructura narrativa en lugar de solo listar datos).",
        "validationTip": "¿La presentación cuenta una historia o es solo una lista de supermercado?",
        "previewResponse": "<div class=\"overflow-x-auto text-[9px]\"><p class=\"font-bold mb-1\">Presentación: El Futuro es Hoy (IA)</p><table class=\"w-full border border-collapse\"><thead><tr class=\"bg-slate-50\"><th>Slide</th><th>Título Impactante</th><th>Guion del Orador</th><th>Imagen Sugerida</th></tr></thead><tbody><tr><td class=\"border p-1\">1</td><td class=\"border p-1\">No es magia, es ahorro.</td><td class=\"border p-1\">\"Hoy no vengo a hablar de robots, sino de cómo ganar 2 horas de vida al día.\"</td><td class=\"border p-1\">Una persona cerrando su laptop feliz al atardecer.</td></tr><tr><td class=\"border p-1\">2</td><td class=\"border p-1\">El Excel ya no es suficiente.</td><td class=\"border p-1\">\"Seguimos usando herramientas del 2005 para problemas del 2025.\"</td><td class=\"border p-1\">Un dinosaurio usando una máquina de escribir.</td></tr><tr><td class=\"border p-1\">3</td><td class=\"border p-1\">Tu nuevo asistente 24/7.</td><td class=\"border p-1\">\"La IA no te va a reemplazar, pero alguien que sabe usarla sí.\"</td><td class=\"border p-1\">Dos manos estrechándose, una humana y una robótica.</td></tr></tbody></table></div>",
        "suggestedAI": "gamma",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 109,
        "category": "productivity",
        "title": "Asistente de Compras \"Smart Buyer\"",
        "icon": "shopping_cart",
        "problem": "Investigación: Parálisis por exceso de opciones al comprar tecnología.",
        "badPrompt": "Dime cuál es la mejor lavadora-secadora.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"La LG WashTower y la Samsung WD22 son buenas opciones. Tienen buena capacidad y ahorro de energía.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1+2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Critique-Based Comparison (Obliga a la IA a buscar puntos débiles, no solo marketing).",
        "validationTip": "¿Te ahorró leer 50 comentarios en Falabella o Mercado Libre?",
        "previewResponse": "<div class=\"text-[10px]\"><p class=\"font-bold mb-1\">Comparativa de Lavadoras-Secadoras (Gama Alta):</p><table class=\"w-full border border-collapse\"><thead><tr class=\"bg-slate-50\"><th>Modelo</th><th>Fortalezas</th><th>Debilidad Real</th><th>Ruido</th></tr></thead><tbody><tr><td class=\"border p-1\"><strong>LG WashTower</strong></td><td class=\"border p-1\">Diseño compacto, IA detecta tela.</td><td class=\"border p-1\">Muy pesada para moverla.</td><td class=\"border p-1\">Ultra silenciosa.</td></tr><tr><td class=\"border p-1\"><strong>Samsung WD22</strong></td><td class=\"border p-1\">Carga gigante (22kg).</td><td class=\"border p-1\">El secado demora más de lo que dicen.</td><td class=\"border p-1\">Moderado.</td></tr><tr><td class=\"border p-1\"><strong>Miele W1</strong></td><td class=\"border p-1\">Dura 20 años.</td><td class=\"border p-1\">Repuestos carísimos en Chile.</td><td class=\"border p-1\">Silenciosa.</td></tr></tbody></table><p class=\"mt-2\"><strong>Veredicto:</strong> Si teletrabajas, la <strong>LG WashTower</strong> es la ganadora. El motor Direct Drive casi no vibra.</p></div>",
        "suggestedAI": "perplexity",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 110,
        "category": "productivity",
        "title": "Prompt de Limpieza de Bases de Datos (Excel)",
        "icon": "data_table",
        "problem": "Data: Bases de datos \"sucias\" que impiden trabajar en CRM.",
        "badPrompt": "Arregla esta lista de nombres y teléfonos.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Aquí tienes la lista: Juan Pérez +569123..., Maria Paz 9876...\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1+5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Data Normalization & Pattern Recognition (Usa reglas lógicas para estandarizar información dispersa).",
        "validationTip": "¿Puedes importar este resultado directamente a tu Excel sin errores?",
        "previewResponse": "<div class=\"bg-slate-900 text-green-400 p-2 font-mono text-[9px] rounded\"><p>Nombre,Telefono,Email,Estado</p><p>Juan Perez,+56 9 1234 5678,juan@gmail.com,OK</p><p>Maria Paz,+56 9 8765 4321,m.paz@outlook.com,OK</p><p>Luis Soto,+56 9 5555 4444,lsoto(at)web.cl,ERROR_EMAIL</p><p class=\"mt-1 text-slate-400 italic\">*Nota: He corregido 4 teléfonos que no tenían el código de Chile.*</p></div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 201,
        "category": "finance",
        "title": "Analista Buffett",
        "icon": "trending_up",
        "problem": "Inversión: Análisis Balance.",
        "badPrompt": "¿Invierto en esta empresa? Mira los números.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Sí, se ve bien.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1+a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Busca deuda alta.",
        "validationTip": "Veredicto numérico.",
        "previewResponse": "<p class=\"text-xs\"><strong>Veredicto:</strong> <span class=\"bg-red-100 text-red-800 font-bold\">RIESGO</span>. Deuda supera 3x el patrimonio.</p>",
        "suggestedAI": "claude",
        "locked": true,
        "isTool": false,
        "difficulty": "advanced"
    },
    {
        "id": 202,
        "category": "finance",
        "title": "Bola de Nieve",
        "icon": "snowboarding",
        "problem": "Deudas: Plan de pago.",
        "badPrompt": "Tengo muchas deudas, ayúdame.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Paga la más grande primero.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX19d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Victorias rápidas.",
        "validationTip": "Fecha libertad.",
        "previewResponse": "<table class=\"w-full text-[10px] border\"><tr><td>Mes 1</td><td>Pagar Tarjeta A</td></tr></table>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 203,
        "category": "finance",
        "title": "Broker Hipotecario",
        "icon": "real_estate_agent",
        "problem": "Inmobiliario: Elegir crédito.",
        "badPrompt": "¿Banco A (4.5%) o Banco B (4.7%)?",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Banco A porque la tasa es menor.\" (Error: Ignora seguros)</div>",
        "agiaPromptTagged": "U2FsdGVkX1/g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Mira el CAE.",
        "validationTip": "Seguro desgravamen.",
        "previewResponse": "<p class=\"text-xs text-green-700 font-bold\">Gana Banco B. Ahorro total: $2.5M (por seguros más baratos).</p>",
        "suggestedAI": "gemini",
        "locked": false,
        "isTool": false,
        "difficulty": "advanced"
    },
    {
        "id": 204,
        "category": "finance",
        "title": "Calculadora FIRE",
        "icon": "savings",
        "problem": "Retiro: Jubilar joven.",
        "badPrompt": "¿Cuánto necesito para jubilarme a los 40?",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Mucho dinero, ahorra harto.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Gasto x 300.",
        "validationTip": "Tasa retiro 4%.",
        "previewResponse": "<div class=\"bg-slate-50 p-2 text-xs\">Meta: <strong>$300,000 USD</strong>. Faltan: 14 años.</div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 205,
        "category": "finance",
        "title": "Comparador Seguros",
        "icon": "health_and_safety",
        "problem": "Seguros: ¿Cuál elijo?",
        "badPrompt": "¿Plan barato con copago alto o plan caro con copago bajo?",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Mejor el plan caro por si acaso.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Calcula gasto anual.",
        "validationTip": "Considera urgencias.",
        "previewResponse": "<p class=\"text-xs\">Si vas al médico menos de 8 veces al año, <strong>elige el Plan Barato</strong>.</p>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 206,
        "category": "finance",
        "title": "Explicador Impuestos",
        "icon": "receipt_long",
        "problem": "Impuestos: ¿Qué es la retención?",
        "badPrompt": "Explícame la retención de boletas fácil.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Es el artículo 42 de la ley de renta...\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Devolución abril.",
        "validationTip": "Previsión social.",
        "previewResponse": "<p class=\"text-xs\">\"El estado te guarda esa plata en una alcancía. En abril la rompen para pagar tu salud...\"</p>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "beginner"
    },
    {
        "id": 207,
        "category": "finance",
        "title": "Evaluador Proyectos",
        "icon": "calculate",
        "problem": "Negocios: ¿Es rentable?",
        "badPrompt": "Quiero vender completos. ¿Es buen negocio?",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Sí, a la gente le gusta comer.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Costos fijos vs variables.",
        "validationTip": "Meses retorno.",
        "previewResponse": "<p class=\"text-xs\">Necesitas vender <strong>1,000 completos</strong> para recuperar tu inversión inicial.</p>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },
    {
        "id": 208,
        "category": "finance",
        "title": "Gastos Hormiga",
        "icon": "coffee",
        "problem": "Ahorro: Café diario.",
        "badPrompt": "Gasto mucho en café. ¿Importa?",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Sí, deberías ahorrar.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Interés compuesto.",
        "validationTip": "Costo oportunidad.",
        "previewResponse": "<p class=\"text-xs font-bold text-red-600\">Estás perdiendo $15 Millones (el valor de un auto nuevo).</p>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "beginner"
    },
    {
        "id": 209,
        "category": "finance",
        "title": "Negociador Deuda",
        "icon": "call_made",
        "problem": "Deudas: Repactar.",
        "badPrompt": "No puedo pagar la cuota este mes. ¿Qué digo?",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Perdón, no tengo plata.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Muestra voluntad.",
        "validationTip": "Pide opciones.",
        "previewResponse": "<div class=\"bg-white p-2 text-xs border border-indigo-100\">\"Tengo toda la intención de pagar, pero necesito reprogramar...\"</div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "advanced"
    },
    {
        "id": 210,
        "category": "finance",
        "title": "Diversificación",
        "icon": "pie_chart",
        "problem": "Inversión: Portafolio.",
        "badPrompt": "Tengo 10 millones. ¿Dónde los pongo?",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Compra Bitcoin.\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/12a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Renta fija vs variable.",
        "validationTip": "ETFs.",
        "previewResponse": "<p class=\"text-xs\">40% S&P500 (Crecimiento) | 40% Depósitos (Seguridad) | 20% Caja.</p>",
        "suggestedAI": "gemini",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    },

    // ==========================================
    // 🎨 ARTE, 🔥 VENTAS, ETC. (El resto de los IDs siguen la misma lógica, omitidos aquí para no exceder token limits)
    // ==========================================

    {
        "id": 301,
        "category": "sales",
        "title": "El \"Rompehielo\" B2B",
        "icon": "mail",
        "problem": "Ventas: Conseguir reunión.",
        "badPrompt": "Escribe un correo para vender mi software de recursos humanos a gerentes.",
        "badResponsePreview": "<div class=\"text-xs text-slate-500 italic\">\"Estimado Gerente, le escribo para presentarle...\"</div>",
        "agiaPromptTagged": "U2FsdGVkX1/b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a7b8c9d0e1f2g3h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7p8q9r",
        "exampleTip": "Chain of Thought + Framework PAS.",
        "validationTip": "¿El asunto parece escrito por un colega o por una máquina de spam?",
        "previewResponse": "<div class=\"bg-white p-3 text-xs font-mono border border-slate-200 shadow-sm rounded-sm text-slate-800\"><div class=\"border-b pb-2 mb-2\"><span class=\"text-slate-500\">Asunto:</span> dudas con la nómina</div><p class=\"mb-2\">Hola [Nombre],</p><p class=\"mb-2\">Gestionar la nómina en Excel funciona bien cuando sois 10 personas, pero con 50 empleados se vuelve una bomba de tiempo de errores manuales.</p><p class=\"mb-2\">De hecho, acabamos de ayudar a una empresa similar a reducir 12 horas semanales de carga administrativa automatizando este proceso.</p><p>¿Te parece mal si te robo 7 minutos el martes para mostrarte cómo lo hicieron?</p></div>",
        "suggestedAI": "chatgpt",
        "locked": false,
        "isTool": false,
        "difficulty": "intermediate"
    }
];

export default allCases;
