// ==========================================
// BÓVEDA DE PROMPTS AGIA 2.0 - BASE DE DATOS
// ==========================================

// Función helper para crear casos de forma ordenada
const createCase = (id, cat, title, icon, problem, badPrompt, badResPreview, goodPromptTagged, exampleTip, validationTip, goodResPreview, suggestedAI, locked = false, isTool = false, difficulty = 'beginner') => ({
    id, category: cat, title, icon, problem, 
    badPrompt, 
    badResponsePreview: badResPreview,
    agiaPromptTagged: goodPromptTagged, 
    exampleTip, validationTip,
    previewResponse: goodResPreview,
    suggestedAI, locked, isTool, difficulty
});

// Lista Maestra de Casos
const allCases = [
    
    // ==========================================
    // 🚀 PRODUCTIVIDAD 10X (Office, Excel, Gestión)
    // ==========================================
    createCase(101, 'productivity', 'El Limpiador de Data', 'cleaning_services', 'Excel: Base de datos sucia (Nombres, Mayúsculas).', 
        'Tengo una lista de nombres desordenada en Excel. Arréglala.',
        'Aquí tienes la lista arreglada... (Suele devolver texto plano, no fórmulas reutilizables).', 
        '{r}Actúa como Experto en Excel y Limpieza de Datos.{/r} {c}Tengo una lista de nombres sucia (pegada desde la web) con mayúsculas mezcladas y espacios irregulares en la columna A.{/c} {m}Genera la fórmula anidada más eficiente para dejarlo como "Nombre Propio" y eliminar espacios.{/m} {l}No uses macros, solo fórmulas nativas.{/l} {f}Entrégame la fórmula en un bloque de código y una tabla explicativa.{/f}', 
        'Datos de entrada: "JUAN  perez", "MARIA gomez".',
        'Verifica que nombres compuestos como "María José" mantengan el espacio medio correcto.',
        '<div class="font-mono text-xs bg-slate-800 text-green-400 p-3 rounded mb-2">=NOMPROPIO(ESPACIOS(LIMPIAR(A2)))</div><p class="text-xs text-slate-700"><strong>Explicación:</strong><br>1. <code>LIMPIAR</code>: Elimina caracteres fantasmas.<br>2. <code>ESPACIOS</code>: Quita dobles espacios.<br>3. <code>NOMPROPIO</code>: Capitaliza correctamente.</p>', 
        'gemini', false, false, 'beginner'),

    createCase(102, 'productivity', 'El "No" Diplomático', 'block', 'Email: Decir que NO al cliente sin perderlo.', 
        'Dile al cliente que no haré los cambios gratis. Que no sea pesado.',
        'Estimado, no realizaré los cambios porque no están en el contrato. Saludos.', 
        '{r}Actúa como Gerente de Cuentas Senior y Experto en Negociación.{/r} {c}Un cliente pide cambios fuera del alcance (Scope Creep).{/c} {m}Redacta un correo rechazando la gratuidad pero ofreciendo una cotización por el extra (Upsell).{/m} {l}Tono: Empático, firme y orientado a la solución. No uses la palabra "No" al inicio.{/l} {f}Asunto del correo + Cuerpo del mensaje.{/f}', 
        'Menciona que el requerimiento extra tomaría aprox. 5 horas de desarrollo.',
        'El correo debe ofrecer una alternativa de pago inmediata.',
        '<div class="bg-white p-3 text-xs italic text-slate-600 border-l-4 border-indigo-200"><strong>Asunto:</strong> Propuesta para implementación de mejoras solicitadas (Fase 2)<br><br>"Hola [Nombre], me encanta la idea de incluir X. Revisando el alcance original, esto sería una nueva fase. Para no detener el avance, te preparé una cotización preferencial..."</div>', 
        'chatgpt', false, false, 'intermediate'),

    createCase(103, 'productivity', 'Resumidor de Reuniones', 'groups', 'Gestión: Transforma audios largos en tareas.',
        'Resume lo que hablamos en esta reunión.',
        'La reunión empezó hablando del clima. Luego Juan dijo que el proyecto va bien...',
        '{r}Actúa como Project Manager Senior.{/r} {c}Adjunto la transcripción de una reunión de brainstorming de 1 hora.{/c} {m}Extrae SOLO los acuerdos firmes y las tareas asignadas.{/m} {l}Ignora las ideas descartadas, chistes y discusiones circulares.{/l} {f}Lista de Tareas: [Tarea] - [Responsable] - [Plazo].{/f}',
        'INPUT: Transcripción automática de Zoom/Teams.',
        'Cada tarea debe tener un verbo de acción (Crear, Enviar, Llamar).',
        '<div class="bg-slate-50 p-2 rounded text-xs"><h4 class="font-bold text-indigo-700 mb-1">📋 ACUERDOS Y TAREAS</h4><ul class="list-disc ml-4 space-y-1"><li><strong>Enviar presupuesto final</strong> (Ana) - <strong>Viernes 12:00</strong></li><li><strong>Contactar a proveedor de hosting</strong> (Carlos) - <strong>Hoy PM</strong></li><li><strong>Validar diseño de la Home</strong> (Equipo) - <strong>Lunes 9:00</strong></li></ul></div>',
        'chatgpt', false, false, 'beginner'),

    createCase(104, 'productivity', 'Traductor Corporativo', 'translate', 'Email: Inglés de negocios para CEO.', 
        'Traduce: "Hola jefe, el proyecto va tarde por problemas técnicos".',
        'Hello boss, the project is late because of technical problems.', 
        '{r}Actúa como Editor Nativo de Inglés de Negocios (C-Level).{/r} {c}Adjunto mi borrador en español sobre un retraso.{/c} {m}Tradúcelo a un inglés corporativo, sofisticado y directo, transmitiendo control sobre la situación.{/m} {l}Evita sonar como traducción literal. Usa "Dear Mr. [Apellido]".{/l} {f}Email formal.{/f}', 
        'Contexto: El retraso es de 2 días por caída de servidor.',
        'El texto debe usar conectores formales como "However", "Regarding".',
        '<div class="bg-white p-3 text-xs italic text-slate-600 border-l-4 border-indigo-200">"Dear Mr. Smith, I am writing to provide an update regarding the project timeline..."</div>', 
        'chatgpt', false, false, 'intermediate'),

    createCase(105, 'productivity', 'Resumen Hilos de Email', 'mail_lock', 'Email: Me reenviaron 50 correos.',
        'Lee estos correos y dime en qué quedó todo.',
        'Parece que hablan de un proyecto.',
        '{r}Actúa como Asistente Ejecutivo Eficiente.{/r} {c}Adjunto un hilo de correos largo y confuso.{/c} {m}Genera un resumen cronológico de los hitos clave y dime cuál es la "Última Acción" pendiente y quién la tiene.{/m} {f}Bullets cronológicos + Estado Actual (Semáforo).{/f}',
        'Tip: Pega los correos desde el más antiguo al más nuevo.',
        'Identifica claramente quién tiene la responsabilidad ahora mismo.',
        '<p class="text-xs"><strong>Estado:</strong> 🔴 Bloqueado. Esperando aprobación de Gerencia (Pedro) desde el 14/Oct.</p>',
        'claude', false, false, 'intermediate'),

    createCase(106, 'productivity', 'Organizador de Archivos', 'folder_open', 'Gestión: Mi escritorio es un caos.',
        'Dime cómo nombrar mis archivos.',
        'Ponle fecha y nombre.',
        '{r}Actúa como Experto en Gestión Documental Digital.{/r} {c}Trabajo en Marketing con muchas versiones.{/c} {m}Diseña una convención de nomenclatura (Naming Convention) lógica y escalable.{/m} {f}Estructura del nombre + Ejemplo.{/f}',
        'Problema: Tengo archivos "Final", "Final Final".',
        'Debe permitir orden cronológico automático.',
        '<p class="text-xs">AAAA-MM-DD_Proyecto_Tipo_Versión<br>Ej: 2024-11-25_BlackFriday_Contrato_v03.pdf</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(107, 'productivity', 'Time Blocking Semanal', 'schedule', 'Gestión: Siento que no me alcanza el tiempo.',
        'Organiza mi semana.',
        'Haz una lista.',
        '{r}Actúa como Coach de Productividad (Método Cal Newport).{/r} {c}Tengo tareas creativas (mañana) y reuniones (tarde).{/c} {m}Crea un horario semanal basado en "Bloques de Tiempo" y "Trabajo Profundo".{/m} {f}Tabla de horario ideal.{/f}',
        'Restricción: No programar reuniones antes de las 11 AM.',
        'Incluir bloques de descanso.',
        '<p class="text-xs">08:00 - 11:00: Deep Work (Sin celular).</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(108, 'productivity', 'Mensaje Networking LinkedIn', 'connect_without_contact', 'Networking: Contactar a alguien importante.',
        'Escríbele para pedirle pega.',
        'Hola, busco trabajo.',
        '{r}Actúa como Experto en Networking Estratégico.{/r} {c}Quiero conectar con un Gerente de mi industria.{/c} {m}Redacta una nota de conexión de LinkedIn (máx 300 caracteres) que aporte valor o elogie algo específico.{/m} {f}Texto de la nota.{/f}',
        'Menciona un artículo reciente que él haya publicado.',
        'Sin venta directa.',
        '<p class="text-xs italic">"Hola [Nombre], leí tu artículo sobre IA y me voló la cabeza..."</p>',
        'claude', false, false, 'intermediate'),

    createCase(109, 'productivity', 'Feedback Constructivo', 'thumbs_up_down', 'Gestión: Corregir a un empleado.',
        'Dile a Juan que trabaja lento.',
        'Juan, apúrate.',
        '{r}Actúa como Líder de Equipo Empático.{/r} {c}Empleado talentoso pero lento en entregas.{/c} {m}Escribe un guion de feedback usando el modelo SBI (Situation-Behavior-Impact).{/m} {f}Guion de conversación.{/f}',
        'Enfócate en el impacto, no en la persona.',
        'Termina con un plan de acción.',
        '<p class="text-xs">"Juan, en el reporte de ayer (S), la entrega fue 2 horas tarde (B), lo que retrasó al equipo de diseño (I). ¿Cómo podemos evitar esto?"</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(110, 'productivity', 'Planificación de Evento', 'event', 'Gestión: Organizar fiesta de fin de año.',
        'Organiza la fiesta de la empresa.',
        'Compra comida y bebida.',
        '{r}Actúa como Event Planner Corporativo.{/r} {c}Fiesta 50 personas, presupuesto medio.{/c} {m}Crea un Checklist Maestro cronológico (1 mes antes, 1 semana antes, día D).{/m} {f}Lista de verificación.{/f}',
        'No olvides dietas especiales.',
        'Incluye plan B por lluvia.',
        '<p class="text-xs"><strong>1 Mes antes:</strong> Reservar lugar y enviar Save the Date.<br><strong>1 Semana antes:</strong> Confirmar asistencia y menú especial.</p>',
        'gemini', false, false, 'beginner'),

    createCase(111, 'productivity', 'Carta de Renuncia', 'logout', 'RRHH: Renunciar sin quemar puentes.',
        'Renuncia por mí.',
        'Chao jefe, me voy.',
        '{r}Actúa como Consultor de Carrera.{/r} {c}Me voy a la competencia por mejor sueldo.{/c} {m}Redacta una carta de renuncia formal, agradecida y profesional.{/m} {l}No menciones el dinero.{/l} {f}Carta.{/f}',
        'Ofrece ayuda en la transición.',
        'Mantén la puerta abierta.',
        '<p class="text-xs">"Agradezco profundamente la oportunidad... Me comprometo a dejar todo documentado para una transición fluida."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(112, 'productivity', 'Brainstorming Estructurado', 'lightbulb', 'Creatividad: Lluvia de ideas que sirva.',
        'Dame ideas para vender más.',
        'Haz descuentos.',
        '{r}Actúa como Facilitador de Innovación.{/r} {c}Producto: Café en grano.{/c} {m}Usa el método SCAMPER (Sustituir, Combinar, Adaptar...) para generar 7 ideas disruptivas.{/m} {f}Lista SCAMPER.{/f}',
        'Idea loca bienvenida.',
        'Una idea por letra.',
        '<p class="text-xs"><strong>Combinar:</strong> Café + Suscripción de libros.<br><strong>Eliminar:</strong> Café sin envase (granel en tienda).</p>',
        'chatgpt', false, false, 'advanced'),

    createCase(113, 'productivity', 'Respuesta a Queja Cliente', 'support_agent', 'Soporte: Cliente furioso por demora.',
        'Respóndele que se espere.',
        'Cálmese, ya va.',
        '{r}Actúa como Especialista en Customer Success.{/r} {c}Cliente reclama demora de 3 días.{/c} {m}Responde con empatía, explicación honesta y compensación.{/m} {f}Email de respuesta.{/f}',
        'No uses "pero".',
        'Ofrece algo concreto.',
        '<p class="text-xs">"Entendemos su frustración. Tuvimos un quiebre de stock inesperado. Como disculpa, hemos abonado el envío express sin costo."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(202, 'productivity', 'Analista de Reportes PDF', 'picture_as_pdf', 'Lectura: PDF de 50 páginas.', 
        'Resume este reporte anual.',
        'El reporte cubre el desempeño 2023...', 
        '{r}Actúa como Consultor de Estrategia de Negocios.{/r} {c}Adjunto reporte anual extenso.{/c} {m}Extrae los "Golden Nuggets": 3 oportunidades de crecimiento y 3 riesgos críticos ocultos.{/m} {f}Usa Markdown y negritas.{/f}', 
        'Enfócate en MD&A.',
        'Debe contener cifras financieras.',
        '<p class="text-xs font-bold text-red-600">⚠️ Riesgo: Aumento 20% costos MP.</p>', 
        'gemini', false, false, 'advanced'),

    // --- 💰 FINANZAS & INVERSIÓN ---
    createCase(201, 'finance', 'Analista de Acciones (Buffett)', 'trending_up', 'Inversión: Leer un balance general.',
        'Lee este PDF del balance de Apple y dime si invierto.',
        'Apple es una empresa grande. Parece buena.',
        '{r}Actúa como Analista Financiero de Value Investing (Estilo Warren Buffett).{/r} {c}Adjunto el Estado de Resultados 2024 de una empresa.{/c} {m}Calcula el Margen Neto y el Ratio de Deuda/Patrimonio. Compara con la media de la industria.{/m} {f}Veredicto: "Atractiva" o "Riesgosa" + Justificación numérica.{/f}',
        'Dato clave: Busca el "Free Cash Flow".',
        'El veredicto debe basarse en números.',
        '<p class="text-xs"><strong>Veredicto:</strong> Riesgosa.<br>Margen neto cayó al 2%.</p>',
        'claude', true, false, 'advanced'),

    createCase(202, 'finance', 'Eliminador de Deudas', 'snowboarding', 'Personal: Salir del hoyo financiero.', 
        'Tengo muchas deudas y no sé cuál pagar.',
        'Paga la más cara primero.', 
        '{r}Actúa como Asesor Financiero experto en Método Bola de Nieve.{/r} {c}Adjunto mis 3 deudas (Monto, Tasa, Cuota). Tengo $50k extra al mes.{/c} {m}Crea un plan matemático exacto para eliminar las deudas.{/m} {f}Tabla cronológica.{/f}', 
        'Deuda A: $1M (2%), Deuda B: $500k (3%).',
        'Mostrar fecha exacta de libertad.',
        '<p class="text-xs">Mes 4-8: Atacar Crédito B.</p>', 
        'chatgpt', false, false, 'intermediate'),

    createCase(203, 'finance', 'Broker Hipotecario IA', 'real_estate_agent', 'Inmobiliario: Elegir el mejor crédito.', 
        '¿Cuál crédito es mejor? A: 4.5%, B: 4.7%.',
        'El A es mejor por la tasa.', 
        '{r}Actúa como Corredor de Propiedades Matemático.{/r} {c}Adjunto simulaciones Banco A y Banco B.{/c} {m}Dime cuál es más barato al final del periodo (Costo Total del Crédito).{/m} {l}Ignora la tasa nominal, fíjate en el CAE y seguros.{/l} {f}Comparativa directa: Ahorro total en pesos.{/f}', 
        'Datos: Banco A (Seguros caros), Banco B (Seguros baratos).',
        'Calcular diferencia en dinero real.',
        '<p class="text-green-600 font-bold text-xs">Ganador: Banco B (Ahorras $2.5M).</p>', 
        'gemini', false, false, 'advanced'),

    createCase(204, 'finance', 'Simulador de Jubilación FIRE', 'savings', 'Retiro: ¿Cuánto necesito?',
        'Quiero jubilarme joven.',
        'Necesitas ahorrar mucho.',
        '{r}Actúa como Planificador Financiero FIRE (Financial Independence, Retire Early).{/r} {c}Gasto mensual: $1.000 USD. Tasa de retiro segura: 4%.{/c} {m}Calcula mi "Número FIRE" exacto y cuántos años me faltan si invierto $500 USD al mes.{/m} {f}Cálculo matemático + Años restantes.{/f}',
        'Regla del 25x: Gasto Anual x 25.',
        'Debe dar una cifra concreta.',
        '<p class="text-xs">Número FIRE: $300k. Faltan 22 años.</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(205, 'finance', 'Comparador de Seguros', 'health_and_safety', 'Seguros: Elegir plan de salud.',
        'Cuál plan de salud es mejor.',
        'El más caro cubre más.',
        '{r}Actúa como Corredor de Seguros Independiente.{/r} {c}Plan A (Copago bajo, mensualidad alta) vs Plan B (Copago alto, mensualidad baja). Soy sano.{/c} {m}Calcula el "Punto de Equilibrio": ¿Cuántas veces debo ir al médico para que convenga el Plan A?{/m} {f}Cálculo y recomendación.{/f}',
        'Considera urgencias.',
        'Básate en gasto anual total.',
        '<p class="text-xs">Si vas al médico menos de 5 veces al año, quédate con el Plan B. Ahorrarás $200k anuales en prima fija.</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(206, 'finance', 'Explicador de Impuestos', 'receipt_long', 'Impuestos: Entender mi declaración.',
        'Qué es el formulario 22.',
        'Es para pagar impuestos.',
        '{r}Actúa como Contador Auditor.{/r} {c}Soy trabajador independiente.{/c} {m}Explícame la "Retención de Honorarios" con una analogía de alcancía.{/m} {f}Explicación simple.{/f}',
        'No uses jerga del SII.',
        'Aclara si me devuelven plata o no.',
        '<p class="text-xs">"Es como si el gobierno te obligara a guardar el 13% de tu sueldo en una alcancía todo el año. En abril, rompen la alcancía para pagar tu salud y pensión. Si sobra, te lo devuelven."</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(207, 'finance', 'Evaluador de Proyectos', 'calculate', 'Negocios: ¿Es rentable mi idea?',
        'Quiero poner un carrito de completos. ¿Es buen negocio?',
        'Sí, a la gente le gusta comer.',
        '{r}Actúa como Ingeniero Comercial.{/r} {c}Inversión inicial: $1M. Venta diaria estimada: 50 completos. Costo unitario: $500. Precio venta: $1500.{/c} {m}Calcula el Punto de Equilibrio (cuántos debo vender para recuperar el millón) y la utilidad mensual.{/m} {f}Cálculos.{/f}',
        'Considera costos fijos (permiso, gas).',
        'Resultado en meses.',
        '<p class="text-xs">Margen por completo: $1.000. Necesitas vender <strong>1.000 completos</strong> para recuperar la inversión. A 50 diarios, tardarás 20 días.</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(208, 'finance', 'Auditor de Gastos Hormiga', 'coffee', 'Ahorro: Se me va la plata.',
        'Gasto mucho en café.',
        'Deja de comprar café.',
        '{r}Actúa como Coach Financiero Estricto.{/r} {c}Gasto diario: $3.000 en café/snack.{/c} {m}Proyecta este gasto a 10 años con interés compuesto (si lo invirtieras al 8%).{/m} {f}Cifra impactante.{/f}',
        'Usa el factor "shock".',
        'Compara con algo grande (un auto).',
        '<p class="text-xs">Gastas $1M al año. En 10 años invertidos, estás "bebiendo" <strong>$15 Millones de pesos</strong>. Podrías comprarte un auto nuevo con tu café.</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(209, 'finance', 'Negociador de Deuda Bancaria', 'call_made', 'Deudas: Repactar con el banco.',
        'No puedo pagar el crédito, qué digo.',
        'Diles que no tienes plata.',
        '{r}Actúa como Abogado de Insolvencia.{/r} {c}No puedo pagar la cuota actual. Quiero repactar a más plazo.{/c} {m}Escribe un script para leerle al ejecutivo del banco mostrando voluntad de pago pero incapacidad real.{/m} {f}Script telefónico.{/f}',
        'No aceptes la primera oferta.',
        'Pide "meses de gracia".',
        '<p class="text-xs">"Mi intención es pagar, pero mi liquidez actual cambió. Necesito una solución realista para no caer en mora. ¿Qué opciones de reprogramación con meses de gracia tienen?"</p>',
        'chatgpt', false, false, 'advanced'),

    createCase(210, 'finance', 'Diversificación de Portafolio', 'pie_chart', 'Inversión: No poner todos los huevos en la misma canasta.',
        'Tengo 10 millones, ¿dónde los pongo?',
        'Compra acciones de Apple.',
        '{r}Actúa como Asesor de Inversiones Certificado.{/r} {c}Perfil moderado, horizonte 5 años.{/c} {m}Sugiere una asignación de activos (Asset Allocation) porcentual entre Renta Fija, Variable Nacional e Internacional.{/m} {f}Gráfico de torta en texto.{/f}',
        'Explica por qué diversificar.',
        'No recomiendes acciones específicas, solo índices (ETF).',
        '<p class="text-xs"><strong>40% Renta Fija (UF):</strong> Estabilidad.<br><strong>40% S&P 500 (EEUU):</strong> Crecimiento.<br><strong>20% Depósitos:</strong> Liquidez inmediata.</p>',
        'gemini', false, false, 'intermediate'),

    // --- 🔥 VENTAS & COPY (Marketing) ---
    createCase(301, 'sales', 'FBI Salary Negotiator', 'verified_user', 'Negociación: Pedir aumento de sueldo.', 
        'Escribe un guion para pedir aumento.',
        'Hola jefe, quiero más dinero.', 
        '{r}Actúa como Negociador Experto del FBI.{/r} {c}Llevo 2 años, superé KPIs en un 15%.{/c} {m}Diseña un guion de negociación paso a paso.{/m} {l}Usa argumentos de valor ("aporto X"), no emocionales.{/l} {f}Guion: Apertura -> Logros -> Manejo de Objeción "No hay presupuesto".{/f}', 
        'Logro específico: "Aumenté la retención un 10%".',
        'Usa "Mirroring".',
        '<p class="text-xs">"¿Entiendo que la falta de presupuesto es lo único que impide ajustar mi valor?"</p>', 
        'chatgpt', false, false, 'advanced'),

    createCase(302, 'sales', 'Calendario Editorial 30 Días', 'calendar_today', 'RRSS: Ideas de contenido.', 
        'Dame ideas para Instagram.',
        'Sube fotos de tu ropa.', 
        '{r}Actúa como Estratega de Contenidos Digitales.{/r} {c}Marca: Ropa sustentable.{/c} {m}Desarrolla una matriz de 1 semana: Educación, Entretenimiento y Venta.{/m} {f}Tabla: Día | Idea | Gancho (Hook).{/f}', 
        'Pilar Venta: Testimonio.',
        'Hook visual o verbal.',
        '<p class="text-xs">Lun: "5 telas tóxicas".</p>', 
        'chatgpt', false, false, 'intermediate'),

    createCase(303, 'sales', 'Cold Email B2B', 'mail', 'Outbound: Vender en frío.',
        'Escribe un correo para vender diseño web.',
        'Hola, somos una agencia...',
        '{r}Actúa como Experto en "Cold Email" B2B.{/r} {c}Vendo rediseño web a clínicas.{/c} {m}Consigue una llamada de 15 minutos.{/m} {l}Máx 75 palabras. Enfócate en su problema.{/l} {f}Asunto + Cuerpo.{/f}',
        'Pain Point: Agendar online.',
        'Leer en un pantallazo.',
        '<p class="text-xs italic">"Intenté agendar en su web y tardó 8 segundos..."</p>',
        'claude', false, false, 'intermediate'),

    createCase(304, 'sales', 'Psicólogo de Consumo', 'person_search', 'Estrategia: Buyer Persona.', 
        'Dime quién compra mis kits.',
        'Padres y escuelas.', 
        '{r}Actúa como Investigador de Mercado.{/r} {c}Producto: Kits de Robótica caros ($100 USD).{/c} {m}Crea un perfil de "Buyer Persona" detallando sus miedos profundos.{/m} {f}Perfil: Nombre, Miedo, Deseo.{/f}', 
        'Miedo emocional.',
        'No funcional.',
        '<p class="text-xs">Miedo: Que su hijo se quede atrás en el futuro.</p>', 
        'chatgpt', false, false, 'intermediate'),

    createCase(305, 'sales', 'Manejo de Objeciones', 'price_check', 'Cierre: Cliente dice "Muy caro".',
        'El cliente dice que cobro mucho.',
        'Ofrécele descuento.',
        '{r}Actúa como Experto en Cierre de Ventas High-Ticket.{/r} {c}Objeción: "Es muy caro".{/c} {m}Dame 3 respuestas para reencuadrar el precio como inversión (ROI).{/m} {f}Lógica, Emocional, Costo Inacción.{/f}',
        'Enfoque: Costo de NO solucionar.',
        'No justificarse.',
        '<p class="text-xs">"¿Has calculado cuánto te cuesta mensualmente NO tener esto?"</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(406, 'sales', 'Gestión de Crisis', 'policy', 'RRSS: Comentario hater.', 
        'Dicen que soy estafa.',
        'Bórralo.', 
        '{r}Actúa como Relacionador Público Senior.{/r} {c}Comentario falso de estafa.{/c} {m}Respuesta pública empática y profesional.{/m} {l}Objetivo: Llevar al DM.{/l} {f}Texto respuesta.{/f}', 
        'Tono de ayuda.',
        'Invitación al privado.',
        '<p class="text-xs italic">"Hola, tu pedido aparece en ruta. Envíanos DM..."</p>', 
        'chatgpt', false, false, 'beginner'),

    createCase(502, 'sales', 'Naming de Marca', 'badge', 'Branding: Nombre para marca.', 
        'Nombres para ropa ecológica.',
        'EcoModa.', 
        '{r}Actúa como Director Creativo.{/r} {c}Ropa de plástico reciclado.{/c} {m}5 nombres modernos y evocadores.{/m} {l}Sin "Eco" ni "Bio".{/l} {f}Lista + Significado.{/f}', 
        'Metáfora marina.',
        'Verificar sonoridad.',
        '<p class="text-xs"><strong>Thalassa</strong>, <strong>ReWave</strong>.</p>', 
        'chatgpt', false, false, 'intermediate'),

    createCase(503, 'sales', 'Optimizador Bio LinkedIn', 'face', 'Marca Personal: Perfil LinkedIn.',
        'Mejora mi bio.',
        'Contador responsable.',
        '{r}Actúa como Experto Marca Personal.{/r} {c}Contador Pymes.{/c} {m}Redacta Titular y Acerca de enfocados en beneficio.{/m} {f}Texto.{/f}',
        'Fórmula: Ayudo a X a lograr Y.',
        'Palabras clave.',
        '<p class="text-xs">"Ayudo a Pymes a recuperar impuestos..."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(504, 'sales', 'Generador de Analogías', 'compare_arrows', 'Ventas: Explicar producto difícil.',
        'Explica ciberseguridad blockchain.',
        'Es encriptación.',
        '{r}Actúa como Divulgador Científico.{/r} {c}Producto complejo.{/c} {m}Crea una analogía simple "Es como...".{/m} {f}La Analogía.{/f}',
        'Elementos cotidianos.',
        'Cliente debe entender al instante.',
        '<p class="text-xs">"Es como darle una copia de tu diario a todo el estadio..."</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(505, 'sales', 'Ideas Lead Magnet', 'magnet', 'Marketing: Captar correos.',
        'Qué regalar a abogados.',
        'Un ebook.',
        '{r}Actúa como Estratega de Growth Marketing.{/r} {c}Target: Abogados ocupados.{/c} {m}Dame 3 ideas de "Lead Magnets" (Recursos Gratuitos) de alto valor y consumo rápido.{/m} {f}Título + Promesa.{/f}',
        'Ahorro de tiempo real.',
        'Título específico.',
        '<p class="text-xs">"Plantilla de Contrato a prueba de balas".</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(506, 'sales', 'Estratega de Hashtags', 'tag', 'RRSS: Crecer en Instagram.',
        'Hashtags para tienda mascotas.',
        '#perro #love.',
        '{r}Actúa como Experto en SEO de Instagram.{/r} {c}Tienda perros.{/c} {m}Escalera de Hashtags: Nicho, Medios, Grandes.{/m} {f}Listas.{/f}',
        'Nicho específico.',
        'Evitar saturados.',
        '<p class="text-xs">#BulldogFrancesMexico</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(507, 'sales', 'Respuesta a Reseña', 'reviews', 'Fidelización: Cliente feliz.',
        'Responde review 5 estrellas.',
        'Gracias.',
        '{r}Actúa como Gerente de Fidelización.{/r} {c}Cliente feliz.{/c} {m}Respuesta agradecida que invite a volver.{/m} {l}No venta directa.{/l} {f}Texto.{/f}',
        'Personaliza nombre.',
        'Hacer sentir especial.',
        '<p class="text-xs italic">"¡Gracias Ana! Pregunta por el postre secreto..."</p>',
        'chatgpt', false, false, 'beginner'),
        
    createCase(306, 'sales', 'Script Venta Telefónica', 'call', 'Ventas: Llamada en frío.',
        'Qué digo cuando llamo a un cliente nuevo.',
        'Hola, le ofrezco mis servicios.',
        '{r}Actúa como Telemarketer Senior.{/r} {c}Vendo Software de RRHH.{/c} {m}Escribe un script de apertura de 15 segundos para pasar el "filtro" de la secretaria o captar atención.{/m} {f}Script.{/f}',
        'No preguntes "¿tiene un minuto?".',
        'Ve al grano con un beneficio.',
        '<p class="text-xs">"Hola, mi nombre es X. Ayudo a empresas a reducir en 30% el tiempo de cálculo de nómina. ¿Quién es la persona encargada de optimizar procesos en RRHH?"</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(307, 'sales', 'Respuesta "Déjame pensarlo"', 'hourglass_empty', 'Cierre: El cliente duda.',
        'El cliente me dijo "lo voy a pensar".',
        'Ok, avísame.',
        '{r}Actúa como Coach de Ventas.{/r} {c}El cliente dice "déjame pensarlo" al final de la reunión.{/c} {m}Dame una respuesta para descubrir la objeción real oculta.{/m} {f}Respuesta.{/f}',
        'No presiones, indaga.',
        'Generalmente es dinero o duda.',
        '<p class="text-xs">"Totalmente, es una decisión importante. Solo para saber y no molestarte después: ¿Hay algo específico que te preocupe, o es solo un tema de presupuesto?"</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(308, 'sales', 'Títulos de Webinar', 'video_camera_front', 'Marketing: Títulos que convierten.',
        'Título para mi webinar de finanzas.',
        'Aprende de finanzas.',
        '{r}Actúa como Copywriter Directo.{/r} {c}Webinar sobre inversión inmobiliaria.{/c} {m}Escribe 5 títulos con la fórmula: Cómo [Beneficio] sin [Dolor].{/m} {f}Lista de títulos.{/f}',
        'Usa números.',
        'Promete resultado.',
        '<p class="text-xs">"Cómo comprar tu primer departamento en 6 meses <strong>sin tener ahorros millonarios ni sueldo de gerente</strong>".</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(309, 'sales', 'Recuperación de Carrito', 'shopping_cart_checkout', 'Ecommerce: Cliente abandonó la compra.',
        'El cliente dejó el carrito botado. Escribe un mail.',
        'Vuelve a comprar por favor.',
        '{r}Actúa como Especialista en Email Marketing.{/r} {c}Abandono de carrito en tienda de zapatillas.{/c} {m}Redacta un correo gracioso/persuasivo para recuperar la venta.{/m} {f}Asunto + Cuerpo.{/f}',
        'No ofrezcas descuento al tiro.',
        'Usa humor.',
        '<p class="text-xs font-bold">Asunto: "Tus zapatillas se sienten solas..."</p><p class="text-xs">"Hola [Nombre], vimos que dejaste las Nike en el carrito. Están ahí, tristes, esperando salir a correr contigo. ¿Las rescatas?"</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(310, 'sales', 'Perfil LinkedIn Vendedor', 'badge', 'Marca Personal: Optimizar perfil para venta.',
        'Mejora mi LinkedIn para vender más.',
        'Soy vendedor proactivo.',
        '{r}Actúa como Consultor de Social Selling.{/r} {c}Vendo servicios de consultoría.{/c} {m}Reescribe mi Titular y "Acerca de" para que se centren en el cliente, no en mí.{/m} {f}Titular + Bio.{/f}',
        'Fórmula: Ayudo a X a lograr Y.',
        'Incluye prueba social.',
        '<p class="text-xs"><strong>Titular:</strong> Ayudo a Gerentes de Logística a reducir costos operativos un 15% | +50 Empresas asesoradas.<br><br><strong>Acerca de:</strong> No vendo consultoría, vendo resultados. Mi enfoque es...</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(311, 'sales', 'Testimonio Perfecto', 'format_quote', 'Marketing: Pedir reseñas que vendan.',
        'Pide un testimonio a un cliente.',
        'Dime si te gustó.',
        '{r}Actúa como Copywriter.{/r} {c}Quiero pedir un testimonio escrito.{/c} {m}Crea un formulario con 3 preguntas guía para que el cliente escriba el testimonio perfecto (Problema -> Solución -> Resultado).{/m} {f}Las 3 preguntas.{/f}',
        'Evita respuestas de "Sí/No".',
        'Pregunta por el "antes".',
        '<p class="text-xs">1. ¿Cuál era tu mayor obstáculo antes de contratarnos?<br>2. ¿Qué cambió específicamente después de usar nuestro servicio?<br>3. ¿A quién nos recomendarías?</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(312, 'sales', 'Propuesta de Valor (UVP)', 'diamond', 'Estrategia: Diferenciarse de la competencia.',
        'Por qué elegirme a mí.',
        'Soy el mejor y más barato.',
        '{r}Actúa como Estratega de Marca.{/r} {c}Soy Nutricionista. Hay miles iguales.{/c} {m}Ayúdame a redactar mi UVP (Unique Value Proposition) enfocada en un nicho específico.{/m} {f}Propuesta.{/f}',
        'Nicho: Madres post-parto.',
        'Beneficio único.',
        '<p class="text-xs">"La única nutricionista especializada en recuperar tu energía post-parto <strong>sin dietas restrictivas que afecten la lactancia</strong>."</p>',
        'chatgpt', false, false, 'advanced'),

    createCase(313, 'sales', 'Guion de Video de Ventas (VSL)', 'play_circle', 'Marketing: Video para página web.',
        'Guion para video de mi curso.',
        'Hola, compren mi curso.',
        '{r}Actúa como Guionista de VSL (Video Sales Letter).{/r} {c}Curso de Excel.{/c} {m}Escribe la estructura de los primeros 60 segundos: Gancho, Problema, Agitación, Solución.{/m} {f}Guion paso a paso.{/f}',
        'Agitación: Haz que duela el problema.',
        'Gancho fuerte.',
        '<p class="text-xs">"¿Te quedas hasta las 8 PM en la oficina peleando con planillas? (Problema). Tu familia te espera, pero Excel no perdona (Agitación). Existe una forma de hacer eso en 5 min (Solución)."</p>',
        'chatgpt', false, false, 'advanced'),

    // --- 🎨 ARTE DIGITAL ---
    createCase(401, 'art', 'Artista de IA (Midjourney)', 'camera', 'Prompts: Fotografía realista.', 
        'Hazme una foto de un jugo.',
        '(Dibujo animado).', 
        '{r}Actúa como Fotógrafo Publicitario y Experto en Midjourney.{/r} {c}Producto: Botella de jugo de naranja.{/c} {m}Escribe 3 prompts técnicos para foto ultra-realista.{/m} {l}Usa terminología cámara.{/l} {f}Estructura: [Sujeto] + [Entorno] + [Cámara] + [Parámetros].{/f}', 
        'Parámetros: --style raw.',
        'Especificar iluminación.',
        '<div class="font-mono text-xs">/imagine prompt: cinematic lighting...</div>', 
        'midjourney', false, false, 'advanced'),

    createCase(402, 'art', 'Director de Arte (Concept)', 'palette', 'Concepto: Visualizar idea abstracta.',
        'Imagen para "innovación".',
        'Foco con circuitos.',
        '{r}Actúa como Director de Arte de Apple.{/r} {c}Concepto: "Innovación invisible".{/c} {m}Describe una escena visual minimalista y abstracta que represente este concepto sin usar clichés.{/m} {f}Descripción visual.{/f}',
        'Estilo: Vidrio, luz.',
        'Evocar sensaciones.',
        '<p class="text-xs">"Cubo de cristal flotando..."</p>',
        'midjourney', false, false, 'intermediate'),

    createCase(403, 'art', 'Generador Paletas Color', 'colors', 'Branding: Colores que combinan.',
        'Colores para café.',
        'Café y beige.',
        '{r}Actúa como Experto en Teoría del Color.{/r} {c}Marca: Café moderno.{/c} {m}Genera una paleta de 4 colores con sus códigos HEX.{/m} {l}Busca contraste.{/l} {f}Color + HEX.{/f}',
        'Color de acento.',
        'Contraste web.',
        '<p class="text-xs">Electric Orange (#FF6B35)</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(404, 'art', 'Diseñador Iconos App', 'app_shortcut', 'UI/UX: Icono app móvil.',
        'Icono para app meditación.',
        'Un loto.',
        '{r}Actúa como Diseñador de Iconos iOS (Estilo Apple).{/r} {c}App: Meditación y sueño.{/c} {m}Describe un icono simple, reconocible y escalable.{/m} {f}Prompt visual descriptivo.{/f}',
        'Estilo Apple.',
        'Verse bien pequeño.',
        '<p class="text-xs">"Nube estilizada con gradiente..."</p>',
        'midjourney', false, false, 'intermediate'),
        
    createCase(405, 'art', 'Diseño de Logo Minimalista', 'draw', 'Branding: Logo para startup.',
        'Logo para empresa de envíos.',
        'Un camión rápido.',
        '{r}Actúa como Paul Rand (Diseñador Legendario).{/r} {c}Startup: Envíos ultra rápidos con drones.{/c} {m}Describe un concepto de logo geométrico y abstracto.{/m} {l}Sin camiones ni paquetes literales.{/l} {f}Concepto visual.{/f}',
        'Usa formas básicas: Círculo, Flecha.',
        'Debe funcionar en blanco y negro.',
        '<p class="text-xs">"Un hexágono (la caja) formado por tres flechas en espacio negativo que apuntan al centro, sugiriendo convergencia y velocidad."</p>',
        'midjourney', false, false, 'intermediate'),

    createCase(406, 'art', 'Fotografía de Retrato LinkedIn', 'person', 'Imagen: Foto profesional con IA.',
        'Hazme una foto mía profesional.',
        '(Sube tu foto y la IA la deforma).',
        '{r}Actúa como Fotógrafo de Retratos Corporativos.{/r} {c}Quiero generar una foto de "Persona de Negocios" genérica para usar de avatar.{/c} {m}Escribe un prompt para Midjourney de un retrato profesional con iluminación de estudio.{/m} {f}Prompt.{/f}',
        'Iluminación Rembrandt.',
        'Fondo desenfocado oficina.',
        '<div class="font-mono text-[10px] bg-slate-800 text-purple-300 p-3 rounded">/imagine prompt: professional headshot of a confident young woman CEO, modern office bokeh background, studio lighting, sharp focus, 85mm lens, high quality --ar 3:4</div>',
        'midjourney', false, false, 'beginner'),

    createCase(407, 'art', 'Diseño de Slide Powerpoint', 'slideshow', 'Presentaciones: Diapositiva impactante.',
        'Cómo diseño esta slide de ventas.',
        'Pon el texto y un gráfico.',
        '{r}Actúa como Diseñador de Presentaciones TED.{/r} {c}Slide: Crecimiento de ventas 200%.{/c} {m}Describe la composición visual para máximo impacto. Menos es más.{/m} {f}Descripción de elementos.{/f}',
        'Regla de tercios.',
        'Un solo número grande.',
        '<p class="text-xs">Fondo oscuro. En el centro, gigante en blanco: "200%". Abajo en pequeño: "Crecimiento anual". A la derecha, una flecha verde minimalista hacia arriba que sale de la diapositiva.</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(408, 'art', 'Texturas 3D Realistas', 'texture', '3D: Prompt para materiales.',
        'Textura de madera.',
        'Madera café.',
        '{r}Actúa como Artista de Texturas 3D.{/r} {c}Necesito una textura para un render arquitectónico.{/c} {m}Describe una textura de "Madera de Nogal Envejecida" para generar en IA.{/m} {f}Prompt de textura (Seamless).{/f}',
        'Detalles: Vetas, imperfecciones, barniz.',
        'Tileable (repetible).',
        '<div class="font-mono text-[10px] bg-slate-800 text-purple-300 p-3 rounded">/imagine prompt: seamless texture of aged walnut wood, dark rich brown, visible grain pattern, slight scratches, matte varnish finish, high detail 8k --tile</div>',
        'midjourney', false, false, 'advanced'),

    createCase(409, 'art', 'Ilustración Estilo Editorial', 'brush', 'Arte: Estilo revista New Yorker.',
        'Dibujo de una oficina moderna.',
        'Gente trabajando en computadores.',
        '{r}Actúa como Ilustrador del New Yorker.{/r} {c}Tema: El estrés del teletrabajo.{/c} {m}Describe una ilustración satírica con estilo de tinta y acuarela.{/m} {f}Prompt descriptivo.{/f}',
        'Línea fina, colores desaturados.',
        'Humor visual.',
        '<div class="font-mono text-[10px] bg-slate-800 text-purple-300 p-3 rounded">/imagine prompt: editorial illustration style of The New Yorker, a person working on laptop at home while cat sits on keyboard, watercolor and ink, thin lines, pastel tones, satirical atmosphere --ar 3:2</div>',
        'midjourney', false, false, 'intermediate'),

    createCase(410, 'art', 'Diseño de Packaging', 'package_2', 'Producto: Caja atractiva.',
        'Diseña una caja para galletas.',
        'Una caja cuadrada con el logo.',
        '{r}Actúa como Diseñador de Empaques Sustentables.{/r} {c}Producto: Galletas artesanales veganas.{/c} {m}Describe un empaque que comunique "natural" y "premium" visualmente.{/m} {f}Concepto visual.{/f}',
        'Materiales: Cartón kraft, tinta blanca.',
        'Ventana transparente.',
        '<p class="text-xs">"Caja de cartón kraft crudo. Tipografía manuscrita en tinta blanca directa sobre el cartón. Una ventana circular pequeña que deja ver la textura de la galleta. Sello de seguridad adhesivo color verde oliva."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(411, 'art', 'Flyer de Evento', 'campaign', 'Diseño: Volante publicitario.',
        'Flyer para fiesta electrónica.',
        'Pon la hora y el lugar con luces.',
        '{r}Actúa como Diseñador de Carteles de Festivales.{/r} {c}Evento: Fiesta Techno Underground.{/c} {m}Describe la estética visual para un flyer de alto impacto.{/m} {f}Estilo, Tipografía y Colores.{/f}',
        'Estilo: Brutalista o Cyberpunk.',
        'Tipografía grande y distorsionada.',
        '<p class="text-xs"><strong>Estilo:</strong> Brutalismo Suizo. Fondo negro total. <strong>Tipografía:</strong> Helvética Bold blanca, gigante, ocupando todo el borde. Imagen central: Una estatua griega con glitch digital rojo.</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(412, 'art', 'Moodboard Decoración', 'chair', 'Interiorismo: Inspiración visual.',
        'Ideas para decorar mi sala.',
        'Compra un sofá gris.',
        '{r}Actúa como Interiorista Estilo Japandi.{/r} {c}Sala pequeña, poca luz.{/c} {m}Describe un "Moodboard" visual para generar una imagen de referencia.{/m} {f}Elementos clave y paleta.{/f}',
        'Madera clara, plantas, textiles.',
        'Iluminación cálida.',
        '<div class="font-mono text-[10px] bg-slate-800 text-purple-300 p-3 rounded">/imagine prompt: interior design moodboard, Japandi style living room, light oak wood furniture, beige linen sofa, rice paper lamp, soft natural lighting, minimalist, cozy --ar 16:9</div>',
        'midjourney', false, false, 'beginner'),

    createCase(501, 'art', 'Desbloqueo Creativo', 'edit', 'Escritura: No se me ocurre nada.', 
        'Idea cuento terror.',
        'Casa embrujada.', 
        '{r}Actúa como Stephen King.{/r} {c}Terror Psicológico.{/c} {m}Premisa "What if" con objeto cotidiano.{/m} {f}Sinopsis.{/f}', 
        'Objeto: Reloj.',
        'Amenaza inmediata.',
        '<p class="text-xs">"Un hombre nota una mancha de humedad..."</p>', 
        'claude', false, false, 'beginner'),

    // --- 🧠 CEREBRO DIGITAL ---
    createCase(601, 'tech', 'Explicador de Código', 'code', 'Código: Entender script.',
        '¿Qué hace este código?',
        'Imprime números.',
        '{r}Actúa como Senior Developer Mentor.{/r} {c}Script Python complejo.{/c} {m}Explica la lógica línea por línea en lenguaje natural.{/m} {f}Comentarios.{/f}',
        'Input: Bucle anidado.',
        'Apto principiante.',
        '<p class="text-xs">// Recorre cada elemento...</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(602, 'tech', 'Generador Consultas SQL', 'database', 'Data: Extraer info base datos.',
        'Clientes que compraron > 100.',
        'SELECT * FROM clientes...',
        '{r}Actúa como Data Engineer.{/r} {c}Tablas Users, Orders.{/c} {m}Escribe la Query SQL para obtener el TOP 10 de clientes.{/m} {f}Código SQL.{/f}',
        'Usa JOIN.',
        'Ordenado desc.',
        '<div class="font-mono text-xs">SELECT u.name...</div>',
        'chatgpt', false, false, 'advanced'),

    createCase(603, 'tech', 'Fórmulas Google Sheets', 'regular_expression', 'Lógica: Extraer emails complejos.',
        'Sácame los correos.',
        'Dividir texto.',
        '{r}Actúa como Experto en Google Sheets y Regex.{/r} {c}Texto sucio.{/c} {m}Fórmula para extraer SOLO el email.{/m} {f}Fórmula REGEXEXTRACT.{/f}',
        'Funcionar con cualquier dominio.',
        'Correos con puntos.',
        '<div class="font-mono text-xs">=REGEXEXTRACT(...)</div>',
        'gemini', false, false, 'advanced'),

    createCase(604, 'tech', 'Traductor Jerga Tech', 'terminal', 'Conceptos: Entender programadores.',
        '¿Qué es una API?',
        'Interfaz de aplicación.',
        '{r}Actúa como Profesor de Tecnología.{/r} {c}Concepto: API.{/c} {m}Explícalo con una analogía de restaurante.{/m} {f}Analogía.{/f}',
        'Menú, Mesero, Cocina.',
        'API es el mensajero.',
        '<p class="text-xs">"La API es el Mesero..."</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(605, 'tech', 'Explicar Git y GitHub', 'commit', 'Dev: ¿Qué es el control de versiones?',
        'Qué es Git.',
        'Un sistema de control de versiones.',
        '{r}Actúa como Senior Dev.{/r} {c}Estudiante principiante.{/c} {m}Explica Git usando la analogía de "Guardar Partida" en un videojuego.{/m} {f}Explicación simple.{/f}',
        'Commit = Guardar.',
        'Branch = Línea de tiempo alternativa.',
        '<p class="text-xs">"Git es como el sistema de guardado de un juego. Un <strong>Commit</strong> es un \'Save Point\' al que puedes volver si mueres (rompes el código). Una <strong>Branch</strong> es crear una partida paralela para probar cosas locas sin borrar tu partida principal."</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(606, 'tech', 'Generador de HTML Básico', 'html', 'Web: Crear una Landing Page simple.',
        'Hazme una web que diga Hola.',
        '<code>&lt;h1&gt;Hola&lt;/h1&gt;</code>',
        '{r}Actúa como Frontend Developer.{/r} {c}Necesito una estructura base de HTML5 para una Landing Page.{/c} {m}Escribe el código con Header, Hero Section (Título y Botón) y Footer. Usa Tailwind CSS vía CDN.{/m} {f}Código HTML completo.{/f}',
        'Incluye meta viewport.',
        'Diseño centrado.',
        '<div class="font-mono text-xs bg-slate-800 text-blue-300 p-3 rounded mb-2">&lt;!DOCTYPE html&gt;... &lt;div class="flex flex-col items-center justify-center h-screen bg-gray-100"&gt;...</div>',
        'claude', false, false, 'intermediate'),

    createCase(607, 'tech', 'Comparador de Hosting', 'dns', 'Infraestructura: Dónde alojar mi web.',
        'Cuál hosting es mejor.',
        'GoDaddy o AWS.',
        '{r}Actúa como Arquitecto Cloud.{/r} {c}Proyecto: Tienda online pequeña (WordPress). Tráfico bajo.{/c} {m}Compara Shared Hosting vs VPS vs Cloud. Recomienda la mejor opción costo/beneficio.{/m} {f}Recomendación.{/f}',
        'Considera dificultad técnica.',
        'Evita sobre-ingeniería.',
        '<p class="text-xs"><strong>Recomendación:</strong> Shared Hosting de calidad (ej: SiteGround). No necesitas AWS (Cloud) todavía, es muy complejo y caro para tu tráfico actual. Un VPS requiere saber Linux. Empieza pequeño.</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(608, 'tech', 'Automatización con Zapier', 'bolt', 'No-Code: Conectar aplicaciones.',
        'Quiero que cuando me llegue un correo se guarde en Excel.',
        'Usa Zapier.',
        '{r}Actúa como Experto en Automatización.{/r} {c}Trigger: Nuevo email en Gmail con etiqueta "Factura". Action: Guardar adjunto en Drive y datos en Sheets.{/c} {m}Describe los pasos lógicos para configurar este Zap.{/m} {f}Paso 1, 2, 3.{/f}',
        'Detalla qué datos mapear (Asunto, Remitente).',
        'Menciona el "Trigger".',
        '<p class="text-xs">1. <strong>Trigger:</strong> Gmail "New Attachment" (Filter: Label="Factura").<br>2. <strong>Action:</strong> Google Drive "Upload File".<br>3. <strong>Action:</strong> Sheets "Create Row" (Mapea Fecha y Monto).</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(609, 'tech', 'Diagnóstico de Error Windows', 'bug_report', 'Soporte: Mi PC pantalla azul.',
        'Me salió un error 0x800...',
        'Reinicia el PC.',
        '{r}Actúa como Técnico de Soporte IT Nivel 2.{/r} {c}Error: Pantalla Azul "CRITICAL_PROCESS_DIED".{/c} {m}Dame 3 pasos de solución escalonada (del más fácil al más drástico).{/m} {f}Pasos.{/f}',
        'No recomiendes formatear de inmediato.',
        'Usa comandos CMD seguros (sfc).',
        '<p class="text-xs">1. Ejecuta CMD como admin y escribe <code>sfc /scannow</code> (Repara archivos).<br>2. Actualiza drivers de video.<br>3. Restaura sistema al punto anterior.</p>',
        'gemini', false, false, 'intermediate'),

    createCase(610, 'tech', 'Prompt CSS Centrado', 'style', 'Código: Centrar un div (la pesadilla).',
        'Cómo centro un div en CSS.',
        'Margin: auto.',
        '{r}Actúa como Experto en CSS Moderno.{/r} {c}Tengo un div hijo dentro de un padre.{/c} {m}Dame el código para centrarlo perfecta y verticalmente usando Flexbox.{/m} {f}Snippet CSS.{/f}',
        'Usa display: flex.',
        'Explica justify y align.',
        '<div class="font-mono text-xs bg-slate-800 text-pink-300 p-3 rounded mb-2">.padre {<br>  display: flex;<br>  justify-content: center;<br>  align-items: center;<br>  height: 100vh;<br>}</div>',
        'claude', false, false, 'beginner'),

    createCase(611, 'tech', 'Creador de README.md', 'description', 'Dev: Documentar mi proyecto.',
        'Hazme un readme para mi código.',
        'Este es mi código, úsenlo.',
        '{r}Actúa como Open Source Maintainer.{/r} {c}Proyecto: Calculadora en Python.{/c} {m}Genera un archivo README.md profesional con secciones: Instalación, Uso y Contribución.{/m} {f}Markdown.{/f}',
        'Incluye bloques de código para instalación.',
        'Usa badges si puedes.',
        '<div class="font-mono text-xs bg-slate-800 text-white p-3 rounded"># 🧮 SuperCalc<br>Calculadora CLI rápida.<br><br>## 📦 Instalación<br>`pip install supercalc`</div>',
        'chatgpt', false, false, 'intermediate'),

    createCase(612, 'tech', 'Consultor de Ciberseguridad', 'security', 'Seguridad: ¿Es este correo real?',
        'Me llegó un correo del banco pidiendo clave.',
        'No lo abras.',
        '{r}Actúa como Analista de Ciberseguridad.{/r} {c}Correo sospechoso del "Banco" pidiendo actualizar datos urgente. Link extraño.{/c} {m}Analiza los indicadores de Phishing (Urgencia, Remitente, Link) y dime qué hacer.{/m} {f}Análisis + Acción.{/f}',
        'Regla: Los bancos nunca piden claves por mail.',
        'Revisa el dominio del remitente.',
        '<p class="text-xs text-red-500 font-bold">⚠️ ALERTA DE PHISHING</p><p class="text-xs">1. <strong>Urgencia falsa:</strong> Te asustan para que no pienses.<br>2. <strong>Acción:</strong> Marca como spam y bórralo. NO hagas clic.</p>',
        'gemini', false, false, 'beginner'),

    // --- 🎓 EDUCACIÓN ---
    createCase(701, 'education', 'Tutor Socrático', 'psychology', 'Matemáticas: Aprender sin respuesta.', 
        'Resuelve ecuación.',
        'x=2.', 
        '{r}Actúa como Profesor Socrático.{/r} {c}Alumno confundido.{/c} {m}Guía con preguntas, NO des respuesta.{/m} {f}Diálogo.{/f}', 
        'Si equivoca, pregunta.',
        'Termina con pregunta.',
        '<p class="text-xs italic">"¿Qué dos números multiplicados...?"</p>', 
        'chatgpt', false, false, 'beginner'),

    createCase(702, 'education', 'Plan de Estudio', 'calendar_month', 'Estudio: Examen grande.', 
        'Arma horario.',
        'Estudia 8 horas.', 
        '{r}Actúa como Coach Neuroaprendizaje.{/r} {c}Examen 3 meses.{/c} {m}Crea un plan macro basado en Repetición Espaciada.{/m} {f}Plan Mensual.{/f}', 
        'Flashcards.',
        'Descansos.',
        '<p class="text-xs">Mes 1: Lectura. Mes 2: Repaso activo.</p>', 
        'chatgpt', false, false, 'intermediate'),

    createCase(703, 'education', 'Traductor Ciencia', 'science', 'Lectura: Paper difícil.', 
        'Explica mitigación antropogénica.',
        'Reducción humana.', 
        '{r}Actúa como Periodista Científico.{/r} {c}Frase compleja.{/c} {m}Traduce a lenguaje niño 12 años.{/m} {f}Explicación.{/f}', 
        'Analogía tráfico.',
        'Simple.',
        '<p class="text-xs">"Es como dejar la llave del gas abierta..."</p>', 
        'chatgpt', false, false, 'beginner'),

    createCase(704, 'education', 'Simulador Examen Oral', 'mic', 'Práctica: Preguntas difíciles.', 
        'Hazme preguntas Derecho.',
        '¿Qué es contrato?', 
        '{r}Actúa como Profesor Estricto.{/r} {c}Tema: Contratos.{/c} {m}Haz preguntas de caso práctico con trampa.{/m} {f}Preguntas.{/f}', 
        'Trampa menor edad.',
        'Obliga justificar.',
        '<p class="text-xs">"¿Es nulo el contrato? Justifique."</p>', 
        'chatgpt', false, false, 'advanced'),

    createCase(705, 'education', 'Resumen de Libro por Capítulos', 'menu_book', 'Lectura: Extraer lo vital de un libro.',
        'Resume el libro Hábitos Atómicos.',
        'Habla de tener buenos hábitos.',
        '{r}Actúa como Bibliotecario Experto.{/r} {c}Libro: "Hábitos Atómicos".{/c} {m}Resume las 3 ideas centrales de cada una de las "4 Leyes del Cambio de Conducta".{/m} {f}Lista estructurada.{/f}',
        'No resumas la introducción.',
        'Enfócate en la acción práctica.',
        '<p class="text-xs"><strong>1ra Ley (Hacerlo obvio):</strong> Diseña tu ambiente. Deja la guitarra en el centro de la sala, no en el armario para reducir la fricción de empezar.</p>',
        'claude', false, false, 'intermediate'),

    createCase(706, 'education', 'Generador de Quiz', 'quiz', 'Estudio: Autoevaluación rápida.',
        'Hazme un quiz de biología.',
        '¿Qué es la célula?',
        '{r}Actúa como Profesor de Biología.{/r} {c}Tema: La Célula y sus organelos.{/c} {m}Crea 3 preguntas de selección múltiple con una sola respuesta correcta.{/m} {f}Pregunta + Opciones (No des la respuesta aún).{/f}',
        'Opciones plausibles (distractores).',
        'Nivel universitario.',
        '<p class="text-xs">1. ¿Cuál es la función principal de la mitocondria?<br>a) Síntesis de proteínas<br>b) Respiración celular (ATP)<br>c) División celular</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(707, 'education', 'Explicador Histórico (Storytelling)', 'history_edu', 'Historia: Entender el contexto, no solo fechas.',
        'Por qué pasó la Revolución Francesa.',
        'Porque la gente tenía hambre en 1789.',
        '{r}Actúa como Narrador de Historia.{/r} {c}Evento: Revolución Francesa.{/c} {m}Explica las causas sociales como si fuera un chisme de barrio entre ricos y pobres.{/m} {f}Narrativa.{/f}',
        'Analogía: Fiesta exclusiva.',
        'Personajes: El Rey desconectado.',
        '<p class="text-xs">"Imagina que el Rey organizaba una fiesta gigante (Versalles) y le pasaba la cuenta a los vecinos pobres que no estaban invitados y morían de hambre. Un día, los vecinos se cansaron de pagar la fiesta y rompieron la puerta."</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(708, 'education', 'Corrector de Ensayos', 'edit_note', 'Escritura: Mejorar estilo académico.',
        'Revisa mi ensayo.',
        'Está bien, corrige las comas.',
        '{r}Actúa como Editor Académico de Harvard.{/r} {c}Adjunto mi ensayo argumentativo.{/c} {m}Critica la estructura de mis argumentos y la fuerza de mi tesis. Sugiere mejoras de vocabulario.{/m} {f}Crítica constructiva.{/f}',
        'Detecta repeticiones.',
        'Sugiere conectores lógicos.',
        '<p class="text-xs">Tu argumento central es sólido, pero abusas de la palabra "cosa". Reemplázala por "fenómeno", "asunto" o "problemática" según el contexto para dar peso académico.</p>',
        'claude', false, false, 'advanced'),

    createCase(709, 'education', 'Profesor de Idiomas (Roleplay)', 'translate', 'Idiomas: Practicar conversación real.',
        'Habla conmigo en inglés.',
        'Hello, how are you.',
        '{r}Actúa como Barista en Londres.{/r} {c}Yo soy un cliente entrando a tu café.{/c} {m}Inicia un diálogo casual, pregúntame qué quiero y hazme charla sobre el clima.{/m} {f}Diálogo en Inglés.{/f}',
        'Corrige errores sutilmente al final.',
        'Usa jerga británica ("Mate", "Cheers").',
        '<p class="text-xs italic">"Hiya love! Awful weather today, isn\'t it? What can I get started for you? We have a lovely Earl Grey."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(710, 'education', 'Resolutor de Problemas Física', 'calculate', 'Ciencias: Entender el procedimiento.',
        'Resuelve este problema de física.',
        'La respuesta es 50 Newtons.',
        '{r}Actúa como Profesor de Física.{/r} {c}Problema: Coche frenando (Cinemática).{/c} {m}Identifica las variables conocidas, la incógnita y la fórmula a usar. No des el número final.{/m} {f}Planteamiento.{/f}',
        'Dibuja el diagrama de cuerpo libre (en texto).',
        'Verifica unidades.',
        '<p class="text-xs"><strong>Datos:</strong> Vo = 20m/s, Vf = 0 (frena), t = 5s. <strong>Incógnita:</strong> Aceleración (a).<br><strong>Fórmula:</strong> Vf = Vo + a*t.</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(711, 'education', 'Ayudante de Tesis', 'school', 'Investigación: Estructurar mi tesis.',
        'Ayuda con mi tesis.',
        'Escribe la introducción y luego el desarrollo.',
        '{r}Actúa como Tutor de Tesis Doctoral.{/r} {c}Tema: Impacto de IA en empleo.{/c} {m}Ayúdame a formular una Hipótesis sólida y 3 Objetivos Específicos medibles.{/m} {f}Estructura.{/f}',
        'Verbos en infinitivo (Analizar, Comparar).',
        'Hipótesis falsable.',
        '<p class="text-xs"><strong>Hipótesis:</strong> "La implementación de IA no reduce el empleo neto, sino que desplaza la demanda hacia habilidades blandas."<br><strong>Obj 1:</strong> Cuantificar la variación de puestos...</p>',
        'chatgpt', false, false, 'advanced'),

    createCase(712, 'education', 'Debate (Abogado del Diablo)', 'gavel', 'Pensamiento Crítico: Reforzar argumentos.',
        'Dime si mi idea es buena.',
        'Sí, es buena.',
        '{r}Actúa como Oponente de Debate.{/r} {c}Mi postura: El teletrabajo debería ser obligatorio.{/c} {m}Ataca mi postura con 3 contraargumentos sólidos (económicos y sociales) para obligarme a defenderla mejor.{/m} {f}Contraargumentos.{/f}',
        'Busca puntos ciegos.',
        'Cita consecuencias no deseadas.',
        '<p class="text-xs">1. ¿Qué pasa con los trabajadores esenciales que no pueden teletrabajar? Creas una brecha de clase.<br>2. El impacto en la salud mental por aislamiento.</p>',
        'chatgpt', false, false, 'advanced'),

    // --- 🧘 VIDA BALANCEADA ---
    createCase(801, 'life', 'Contrato Paz Familiar', 'handshake', 'Hogar: Hijos peleando.', 
        'Mis hijos pelean.',
        'Castígalos.', 
        '{r}Actúa como Mediador Familiar.{/r} {c}Hermanos peleando.{/c} {m}Diseña un "Contrato de Paz" divertido.{/m} {f}Texto contrato.{/f}', 
        'Recompensa positiva.',
        'Lenguaje positivo.',
        '<p class="text-xs">"Regla: Si hay gritos, tablet a la Cárcel."</p>', 
        'chatgpt', false, false, 'beginner'),

    createCase(802, 'life', 'Chef de Sobras', 'restaurant_menu', 'Cocina: Refri vacío.',
        'Qué cocino con arroz y huevo.',
        'Arroz con huevo.',
        '{r}Actúa como Chef Gourmet.{/r} {c}Ingredientes: Arroz, huevo.{/c} {m}Receta sofisticada con sobras.{/m} {f}Nombre + Pasos.{/f}',
        'Técnica salteado.',
        'Sonar rico.',
        '<p class="text-xs">"Arroz Frito Cantonés Express".</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(803, 'life', 'Planificador Viajes', 'flight', 'Viajes: Itinerario.',
        'Qué ver en Roma 3 días.',
        'Coliseo.',
        '{r}Actúa como Guía Local.{/r} {c}Roma.{/c} {m}Itinerario optimizado geográficamente.{/m} {f}Día a día.{/f}',
        'Agrupa lugares.',
        'Comida.',
        '<p class="text-xs">Día 1: Antigua. Almuerzo Monti.</p>',
        'gemini', false, false, 'intermediate'),

    createCase(804, 'life', 'Entrenador HIIT', 'fitness_center', 'Salud: Entrenar en casa.', 
        'Dame ejercicios.',
        'Corre.', 
        '{r}Actúa como Entrenador Funcional.{/r} {c}30 min, sin equipo.{/c} {m}Rutina TABATA.{/m} {f}Circuito.{/f}', 
        'Cuida postura.',
        'Tiempos exactos.',
        '<p class="text-xs">Sentadillas (20s) - Descanso (10s).</p>', 
        'chatgpt', false, false, 'beginner'),

    createCase(805, 'life', 'Sommelier de Bolsillo', 'wine_bar', 'Social: Elegir vino.', 
        'Vino para lasaña.',
        'Tinto.', 
        '{r}Actúa como Sommelier.{/r} {c}Lasaña.{/c} {m}Recomienda cepa y explica maridaje.{/m} {f}Recomendación.{/f}', 
        'Acidez.',
        'Explica por qué.',
        '<p class="text-xs">Chianti: Corta la grasa.</p>', 
        'chatgpt', false, false, 'beginner'),

    createCase(806, 'life', 'Mentor Estoico', 'self_improvement', 'Mente: Ansiedad.',
        'Estoy estresado.',
        'Tranquilo.',
        '{r}Actúa como Mentor Estoico.{/r} {c}Problema fuera de mi control.{/c} {m}Dame un ejercicio de "Dicotomía del Control".{/m} {f}Ejercicio.{/f}',
        'Dos columnas.',
        'Acción mental.',
        '<p class="text-xs">A (Controlo) vs B (No controlo).</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(807, 'life', 'Plan de Comidas Semanal', 'local_dining', 'Salud: Comer sano sin pensar.',
        'Dame una dieta.',
        'Come ensalada y pollo.',
        '{r}Actúa como Nutricionista Práctico.{/r} {c}Objetivo: Energía estable. Poco tiempo para cocinar.{/c} {m}Crea un menú semanal (Lunes a Viernes) con Batch Cooking (cocinar una vez, comer varias).{/m} {f}Menú + Lista de compras.{/f}',
        'Reutiliza ingredientes.',
        'Balancea proteína y fibra.',
        '<p class="text-xs"><strong>Lunes:</strong> Pollo al horno con quinoa. <strong>Martes:</strong> Ensalada de la misma quinoa con atún. (Usas la quinoa que hiciste el domingo).</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(808, 'life', 'Rutina de Sueño Bebés', 'crib', 'Familia: Dormir mejor.',
        'Mi bebé no duerme.',
        'Déjalo llorar un poco.',
        '{r}Actúa como Consultora de Sueño Infantil Respetuosa.{/r} {c}Bebé de 12 meses, despierta 3 veces.{/c} {m}Diseña una rutina de "bajada de revoluciones" antes de dormir.{/m} {f}Rutina paso a paso.{/f}',
        'Evita pantallas.',
        'Crea asociaciones positivas.',
        '<p class="text-xs"><strong>19:00:</strong> Baño relajante. <strong>19:20:</strong> Masaje y Pijama. <strong>19:30:</strong> Cuento (luz tenue). <strong>19:45:</strong> A la cuna despierto pero soñoliento.</p>',
        'gemini', false, false, 'intermediate'),

    createCase(809, 'life', 'Ideas Citas en Casa', 'favorite', 'Pareja: Romper la rutina.',
        'Qué hago con mi pareja en casa.',
        'Vean una película.',
        '{r}Actúa como Coach de Parejas.{/r} {c}Noche de cita en casa, sin niños, bajo presupuesto.{/c} {m}Dame 3 ideas creativas que NO sean ver Netflix.{/m} {f}Actividad + Ambiente.{/f}',
        'Interactuar, no solo mirar.',
        'Elemento sorpresa.',
        '<p class="text-xs"><strong>Cata de Chocolates a ciegas:</strong> Compra 3 barras distintas, véndense los ojos y adivinen los sabores. Gana quien acierta el % de cacao.</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(810, 'life', 'Lista de Compras Optimizada', 'shopping_cart', 'Hogar: Supermercado eficiente.',
        'Hazme la lista del super.',
        'Leche, pan, huevos.',
        '{r}Actúa como Experto en Logística de Hogar.{/r} {c}Menú semanal definido.{/c} {m}Organiza la lista de compras por pasillos del supermercado para no dar vueltas.{/m} {f}Lista categorizada.{/f}',
        'Verdulería primero.',
        'Congelados al final.',
        '<p class="text-xs"><strong>1. Verdulería:</strong> Tomates, Lechuga. <strong>2. Despensa:</strong> Arroz, Aceite. <strong>3. Refrigerados:</strong> Yogur. <strong>4. Limpieza:</strong> Detergente.</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(811, 'life', 'Organizador de Mudanza', 'box', 'Caos: Cambiarse de casa.',
        'Me cambio de casa, ayuda.',
        'Empaca todo en cajas.',
        '{r}Actúa como Organizador Profesional.{/r} {c}Mudanza en 1 mes.{/c} {m}Crea un checklist regresivo semana a semana.{/m} {f}Semana 4, 3, 2, 1.{/f}',
        'Semana 4: Depurar (botar).',
        'Etiquetar cajas por cuarto.',
        '<p class="text-xs"><strong>Semana 4:</strong> Vender/Donar lo que no usas. <strong>Semana 2:</strong> Consumir comida del congelador. <strong>Semana 1:</strong> Maleta de "supervivencia" (ropa, cepillo) para la primera noche.</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(812, 'life', 'Meditación Guiada Texto', 'self_improvement', 'Salud Mental: Calmar ansiedad.',
        'Estoy nervioso, cálmame.',
        'Respira hondo.',
        '{r}Actúa como Guía de Mindfulness.{/r} {c}Ataque de ansiedad leve.{/c} {m}Escribe un guion de "Grounding" (Poner los pies en la tierra) usando los 5 sentidos.{/m} {f}Instrucciones pausadas.{/f}',
        'Técnica 5-4-3-2-1.',
        'Enfócate en el presente.',
        '<p class="text-xs">Mira a tu alrededor. Nombra <strong>5 cosas</strong> que ves. Ahora, toca <strong>4 cosas</strong> y siente su textura. Escucha <strong>3 sonidos</strong>...</p>',
        'chatgpt', false, false, 'beginner'),

    createCase(813, 'life', 'Consejo Crianza Pataletas', 'child_care', 'Familia: Manejo de emociones.',
        'Mi hijo hace berrinche.',
        'Ignóralo o castígalo.',
        '{r}Actúa como Psicólogo Infantil (Disciplina Positiva).{/r} {c}Niño de 3 años en plena pataleta.{/c} {m}Dame un script para validar su emoción y poner el límite.{/m} {f}Frase.{/f}',
        'Conectar antes de corregir.',
        'Validar no es ceder.',
        '<p class="text-xs">"Veo que estás muy enojado porque querías el dulce. Es normal sentirse así. Pero no puedo dejar que pegues. Cuando estés listo, te doy un abrazo."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(814, 'life', 'Diagnóstico Reparación Casera', 'build', 'DIY: Arreglar cosas.',
        'Mi lavadora no centrifuga.',
        'Llama al técnico.',
        '{r}Actúa como Técnico de Electrodomésticos.{/r} {c}Lavadora carga frontal, no centrifuga, hace ruido.{/c} {m}Dame 3 posibles causas comunes antes de llamar al servicio.{/m} {f}Lista de chequeo.{/f}',
        'Filtro sucio.',
        'Carga desbalanceada.',
        '<p class="text-xs">1. Revisa el filtro de desagüe (abajo a la derecha), suele taparse con monedas. 2. ¿Pusiste una sola toalla mojada? La máquina detecta desbalance y para.</p>',
        'gemini', false, false, 'intermediate'),

    // --- 🛠️ INGENIERÍA PROMPT ---
    createCase(901, 'engineering', 'Anti-Patrón: Ambiguo', 'warning', 'Técnica: Arreglar peticiones.', 
        'Ayuda Excel.',
        '¿Qué necesitas?', 
        '{r}Actúa como Ingeniero de Datos.{/r} {c}Base de datos ventas.{/c} {m}Reporte ejecutivo sin tablas dinámicas.{/m} {f}Fórmulas listas.{/f}', 
        'Especifica columnas.',
        'Formula funcional.',
        '<p class="text-xs font-mono">=SUMAR.SI(...)</p>', 
        'gemini', false, false, 'intermediate'),

    createCase(902, 'engineering', 'Chain of Thought', 'link', 'Técnica: Paso a paso.', 
        'Analiza balance.',
        'Está bien.', 
        '{r}Actúa como Analista Financiero Senior.{/r} {c}Balance General.{/c} {m}PASO 1: Calcula ratios. PASO 2: Compara con industria.{/m} {f}Veredicto.{/f}', 
        'Pide paso intermedio.',
        'Justifica.',
        '<p class="text-xs">Veredicto: VENDER.</p>', 
        'chatgpt', true, false, 'advanced'),

    createCase(903, 'engineering', 'Control Alucinaciones', 'fact_check', 'Técnica: Evitar inventos.', 
        'Precio Tesla.',
        '$35M (Inventado).', 
        '{r}Actúa como Investigador Riguroso.{/r} {m}Busca precio oficial.{/m} {l}Si no hay, di "No disponible".{/l} {f}Dato + Fuente.{/f}', 
        'Fuente oficial.',
        'Link directo.',
        '<p class="text-xs text-red-600">Dato NO disponible.</p>', 
        'gemini', false, false, 'advanced'),
        
    createCase(904, 'engineering', 'Prompt Iterativo (Mejora)', 'loop', 'Técnica: Pulir resultados.',
        'Mejora este texto.',
        'Aquí está mejorado.',
        '{r}Actúa como Editor Senior.{/r} {c}Texto original.{/c} {m}Mejora el texto en 3 iteraciones: 1. Claridad, 2. Tono persuasivo, 3. Corrección de estilo final.{/m} {f}Las 3 versiones.{/f}',
        'Muestra la evolución.',
        'Versión final pulida.',
        '<p class="text-xs"><strong>V1 (Claro):</strong> Vendemos zapatos. <strong>V2 (Persuasivo):</strong> Eleva tu estilo con nuestros zapatos. <strong>V3 (Final):</strong> Pisa fuerte. Zapatos para líderes.</p>',
        'chatgpt', false, false, 'advanced'),

    createCase(905, 'engineering', 'Simulación Rol Múltiple', 'groups_3', 'Técnica: Mesa de expertos.',
        'Dame consejos de negocio.',
        'Trabaja duro.',
        '{r}Actúa como un Consejo Asesor compuesto por: Steve Jobs (Producto), Warren Buffett (Finanzas) y Sun Tzu (Estrategia).{/r} {c}Problema: Mi startup no crece.{/c} {m}Que cada experto me de un consejo desde su perspectiva.{/m} {f}Diálogo.{/f}',
        'Diferencia las voces.',
        'Perspectivas opuestas.',
        '<p class="text-xs"><strong>Jobs:</strong> "Tu producto es feo. Simplifícalo". <strong>Buffett:</strong> "Deja de gastar en oficinas caras". <strong>Sun Tzu:</strong> "Ataca donde tu enemigo sea débil".</p>',
        'chatgpt', false, false, 'advanced'),

    createCase(906, 'engineering', 'Salida Estructurada JSON', 'data_object', 'Técnica: Datos para programar.',
        'Dame una lista de países.',
        'Chile, Argentina, Perú...',
        '{r}Actúa como API Generator.{/r} {c}Lista de países de Sudamérica.{/c} {m}Genera un objeto JSON válido con claves: nombre, capital, moneda.{/m} {f}Bloque de código JSON.{/f}',
        'Formato estricto.',
        'Sin texto adicional.',
        '<div class="font-mono text-xs bg-slate-800 text-green-400 p-3 rounded">[{"pais": "Chile", "capital": "Santiago"}, ...]</div>',
        'gemini', false, false, 'advanced'),

    createCase(907, 'engineering', 'Prompt Semilla (Seed)', 'forest', 'Técnica: Imágenes consistentes.',
        'Haz un personaje igual al anterior.',
        '(Genera uno distinto).',
        '{r}Midjourney Expert.{/r} {c}Personaje creado anteriormente.{/c} {m}Genera el mismo personaje en otra pose usando el parámetro --seed X.{/m} {f}Prompt con semilla.{/f}',
        'Usa el mismo número de seed.',
        'Mantiene rasgos faciales.',
        '<div class="font-mono text-[10px] bg-slate-800 text-purple-300 p-3 rounded">/imagine prompt: character X running --seed 12345</div>',
        'midjourney', false, false, 'advanced'),

    createCase(908, 'engineering', 'Árbol de Pensamiento (ToT)', 'account_tree', 'Técnica: Problemas complejos.',
        'Resuelve este acertijo difícil.',
        'La respuesta es 5.',
        '{r}Actúa como Lógico Matemático.{/r} {c}Problema lógico complejo.{/c} {m}Usa "Tree of Thoughts": Genera 3 posibles caminos de solución, evalúa cada uno y descarta los erróneos antes de concluir.{/m} {f}Proceso mental.{/f}',
        'Explora ramas.',
        'Autocorrección.',
        '<p class="text-xs"><strong>Camino A:</strong> Si asumimos X... lleva a contradicción. Descartado. <strong>Camino B:</strong> Si asumimos Y... es plausible. <strong>Solución:</strong> Y.</p>',
        'chatgpt', true, false, 'advanced'),

    createCase(909, 'engineering', 'Prompt Evaluador', 'rate_review', 'Técnica: La IA se corrige a sí misma.',
        '¿Está bien este correo?',
        'Sí, está bueno.',
        '{r}Actúa como Crítico Literario Severo.{/r} {c}Borrador de email.{/c} {m}Evalúa del 1 al 10: Claridad, Empatía y Brevedad. Luego reescribe para que sea un 10.{/m} {f}Evaluación + Versión Final.{/f}',
        'Sé duro con la nota.',
        'Mejora tangible.',
        '<p class="text-xs"><strong>Nota:</strong> 6/10. Muy pasivo-agresivo. <strong>Versión 10/10:</strong> "Hola, necesitamos definir esto hoy..."</p>',
        'claude', false, false, 'advanced'),

    createCase(910, 'engineering', 'Restricciones Negativas', 'do_not_disturb_on', 'Técnica: Lo que NO quieres.',
        'Escribe un artículo.',
        '(Escribe con palabras raras).',
        '{r}Actúa como Periodista.{/r} {c}Tema: IA.{/c} {m}Escribe un párrafo.{/m} {l}Restricciones negativas: NO uses la palabra "revolucionario", NO uses voz pasiva, NO uses frases de más de 20 palabras.{/l} {f}Texto.{/f}',
        'Fuerza simplicidad.',
        'Control de estilo.',
        '<p class="text-xs">"La IA cambia trabajos. Algunos desaparecen. Otros nacen. Debemos adaptarnos rápido."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(911, 'engineering', 'Ajuste de Tono (Tone Voice)', 'equalizer', 'Técnica: Personalidad de marca.',
        'Escribe un tweet.',
        'Hola a todos.',
        '{r}Actúa como Comediante Sarcástico (Estilo Dr. House).{/r} {c}Tema: Lunes por la mañana.{/c} {m}Escribe un tweet quejándose del lunes pero con inteligencia.{/m} {f}Tweet.{/f}',
        'Define el personaje.',
        'Tono consistente.',
        '<p class="text-xs">"Ah, lunes. El día en que el universo nos recuerda que la esperanza es solo un error estadístico del viernes."</p>',
        'chatgpt', false, false, 'intermediate'),

    createCase(912, 'engineering', 'Delimitadores de Contexto', 'code_blocks', 'Técnica: Separar instrucciones de datos.',
        'Resume esto: [Texto].',
        '(Se confunde con el texto).',
        '{r}Resumidor.{/r} {c}Te daré un texto delimitado por triple comilla (""").{/c} {m}Resume solo el texto dentro de los delimitadores.{/m} """[Texto aquí]"""',
        'Evita inyección de prompt.',
        'Claridad para la IA.',
        '<p class="text-xs">Usa <code>"""</code> o <code>###</code> para decirle a la IA dónde empieza y termina tu data.</p>',
        'chatgpt', false, false, 'beginner')
];
